package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"testing/fstest"
)

// generateAgents runs the generator over a directory and gives back what it
// wrote, which is the one file it always produces.
func generateAgents(t *testing.T, dir string) string {
	t.Helper()
	files, err := agents(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || files[0].Path != agentsFile {
		t.Fatalf("the generator wrote %+v, want one %s", files, agentsFile)
	}
	return string(files[0].Data)
}

func TestAgents(t *testing.T) {
	dir := scratch(t, commands)
	got := generateAgents(t, dir)

	for _, want := range []string{
		"<!-- Code generated by mizu gen agents v1; DO NOT EDIT.",
		"# commandtest",
		"Go 1.27, 2 packages, 0 commands.",
		"mizu verify --fix",
		"go test -race ./...",
		"| app       | app     | Package app is a set of commands",
		"| mizu gen command v1 | app/commands_gen.go |",
		keepStart,
		keepEnd,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the file does not contain %q:\n%s", want, got)
		}
	}
	if lines := strings.Count(got, "\n"); lines > 200 {
		t.Errorf("the file is %d lines, and it is meant to stay under 200", lines)
	}
}

// The file describes the whole module, so it cannot depend on which part of it
// somebody asked to generate.
func TestAgentsIgnoresThePackagesItIsGiven(t *testing.T) {
	dir := scratch(t, commands)

	pkgs, err := load(dir, []string{"./broken"})
	if err != nil {
		t.Fatal(err)
	}
	files, err := agents(dir, pkgs...)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := string(files[0].Data), generateAgents(t, dir); got != want {
		t.Errorf("one package gave a different file:\n%s", got)
	}
}

func TestAgentsKeepsWhatIsInTheKeepBlock(t *testing.T) {
	dir := scratch(t, commands)
	const note = "The broken package is meant to be broken. Do not fix it."

	first := generateAgents(t, dir)
	edited := strings.Replace(first, firstNotes, note, 1)
	if edited == first {
		t.Fatal("the first run did not write the notes this test edits")
	}
	add(t, filepath.Join(dir, agentsFile), edited)

	got := generateAgents(t, dir)
	if !strings.Contains(got, note) {
		t.Errorf("the note did not survive:\n%s", got)
	}
	if strings.Contains(got, firstNotes) {
		t.Error("the note was replaced by the one a new file gets")
	}
}

// Running it twice has to give the same file, or a project is never up to date
// and mizu gen --check fails the moment after mizu gen ran.
func TestAgentsSaysTheSameThingTwice(t *testing.T) {
	dir := scratch(t, commands)

	first := generateAgents(t, dir)
	add(t, filepath.Join(dir, agentsFile), first)
	if second := generateAgents(t, dir); second != first {
		t.Errorf("the second run wrote something else:\n%s", second)
	}
}

// The file lists itself. It is written by a generator like the rest of them and
// leaving it out would be the one wrong row in the table.
func TestAgentsListsItself(t *testing.T) {
	dir := scratch(t, commands)
	want := "| mizu gen agents v1  | AGENTS.md           |"

	first := generateAgents(t, dir)
	if !strings.Contains(first, want) {
		t.Errorf("the first run did not list the file it was writing:\n%s", first)
	}
	add(t, filepath.Join(dir, agentsFile), first)
	if second := generateAgents(t, dir); !strings.Contains(second, want) {
		t.Errorf("the second run did not list it either:\n%s", second)
	}
}

func TestAgentsOnAFileSomebodyWroteByHand(t *testing.T) {
	dir := scratch(t, commands)
	add(t, filepath.Join(dir, agentsFile), "# Notes\n\nRead the tracking issue first.\n")

	_, err := agents(dir)
	if err == nil {
		t.Fatal("a hand written file was overwritten without a word")
	}
	for _, want := range []string{"written by hand", "mv AGENTS.md AGENTS.md.old", keepStart} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the error is %q, want it to mention %q", err, want)
		}
	}
}

func TestAgentsOnAKeepBlockThatNeverEnds(t *testing.T) {
	dir := scratch(t, commands)
	add(t, filepath.Join(dir, agentsFile), agentsHeader()+"\n## Notes\n\n"+keepStart+"\n\nA note.\n")

	_, err := agents(dir)
	if err == nil {
		t.Fatal("a keep block with no end was read as though the rest of the file were notes")
	}
	if !strings.Contains(err.Error(), keepEnd) {
		t.Errorf("the error is %q, want it to name the marker that is missing", err)
	}
}

// Somebody who deletes the markers out of a generated file gets them back, since
// everything else in it was written by the generator too.
func TestAgentsOnAGeneratedFileWithNoMarkers(t *testing.T) {
	dir := scratch(t, commands)
	add(t, filepath.Join(dir, agentsFile), agentsHeader()+"\n# commandtest\n")

	if got := generateAgents(t, dir); !strings.Contains(got, firstNotes) {
		t.Errorf("the keep block did not come back:\n%s", got)
	}
}

func TestAgentsWhenTheFileCannotBeRead(t *testing.T) {
	dir := scratch(t, commands)
	name := filepath.Join(dir, agentsFile)
	add(t, name, agentsHeader())
	shut(t, name, 0)

	if _, err := agents(dir); err == nil {
		t.Fatal("a file that cannot be read was replaced anyway")
	}
}

func TestAgentsOnAProjectThatHasNoneYet(t *testing.T) {
	dir := t.TempDir()
	add(t, filepath.Join(dir, "go.mod"), "module example.com/p\n\ngo 1.27\n")

	got := generateAgents(t, dir)
	if !strings.Contains(got, firstNotes) {
		t.Errorf("a new file did not get the keep block:\n%s", got)
	}
	if !strings.Contains(got, "# example.com/p") {
		t.Errorf("a new file does not name the module:\n%s", got)
	}
}

func TestMainPackages(t *testing.T) {
	got := mainPackages([]pkgInfo{
		{Dir: "console", Name: "console"},
		{Dir: "cmd/hello", Name: "main"},
	})
	if len(got) != 1 || got[0].Dir != "cmd/hello" {
		t.Errorf("mainPackages() = %+v, want the one command", got)
	}
}

func TestAgentsWithoutAGoMod(t *testing.T) {
	if _, err := agents(t.TempDir()); err == nil {
		t.Fatal("a directory that is not a module was described as one")
	}
}

func TestReadModule(t *testing.T) {
	tests := []struct {
		name string
		mod  string
		want moduleFacts
	}{
		{
			name: "the whole of what is read",
			mod:  "module example.com/p\n\ngo 1.27\n\nrequire golang.org/x/text v0.41.0\n",
			want: moduleFacts{Path: "example.com/p", Go: "1.27"},
		},
		{
			name: "a requirement that starts with the word go",
			mod:  "module example.com/p\n\nrequire (\n\tgo.uber.org/zap v1.27.0\n)\n\ngo 1.27\n",
			want: moduleFacts{Path: "example.com/p", Go: "1.27"},
		},
		{
			name: "no go directive, which is a module written before 1.12",
			mod:  "module example.com/p\n",
			want: moduleFacts{Path: "example.com/p"},
		},
		{
			name: "a line with nothing after the keyword",
			mod:  "module\nmodule example.com/p\ngo 1.27\n",
			want: moduleFacts{Path: "example.com/p", Go: "1.27"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := readModule(fstest.MapFS{"go.mod": {Data: []byte(tt.mod)}})
			if err != nil {
				t.Fatal(err)
			}
			if got != tt.want {
				t.Errorf("readModule() = %+v, want %+v", got, tt.want)
			}
		})
	}
}

func TestReadModuleWithoutAModuleLine(t *testing.T) {
	_, err := readModule(fstest.MapFS{"go.mod": {Data: []byte("go 1.27\n")}})
	if err == nil {
		t.Fatal("a go.mod naming no module was accepted")
	}
}

func TestPackagesIn(t *testing.T) {
	fsys := fstest.MapFS{
		"go.mod":                  {Data: []byte("module example.com/p\ngo 1.27\n")},
		"doc.go":                  {Data: []byte("// Package p is the root.\npackage p\n")},
		"a.go":                    {Data: []byte("package p\n")},
		"a_test.go":               {Data: []byte("// Package p_test is not a package of its own.\npackage p_test\n")},
		"cmd/hello/main.go":       {Data: []byte("// Command hello says hello.\npackage main\n")},
		"empty/notes.txt":         {Data: []byte("nothing to see\n")},
		"tools/bot/go.mod":        {Data: []byte("module example.com/bot\n")},
		"tools/bot/main.go":       {Data: []byte("// Command bot is a module of its own.\npackage main\n")},
		"tools/bot/run/run.go":    {Data: []byte("package run\n")},
		"testdata/fixture/f.go":   {Data: []byte("package fixture\n")},
		"unparseable/nonsense.go": {Data: []byte("this is not Go at all\n")},
	}

	want := []pkgInfo{
		{Dir: ".", Name: "p", Doc: "Package p is the root."},
		{Dir: "cmd/hello", Name: "main", Doc: "Command hello says hello."},
	}
	got := packagesIn(fsys, nestedModules(fsys))
	if len(got) != len(want) {
		t.Fatalf("packagesIn() = %+v\nwant %+v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("packagesIn()[%d] = %+v, want %+v", i, got[i], want[i])
		}
	}
}

// doc.go is where a package that has a lot to say says it, so it is read first.
func TestPackagesInPrefersDocGo(t *testing.T) {
	fsys := fstest.MapFS{
		"p/a.go":   {Data: []byte("// A comment about the file.\npackage p\n")},
		"p/doc.go": {Data: []byte("// Package p is the one worth reading.\npackage p\n")},
	}
	got := packagesIn(fsys, nil)
	if len(got) != 1 || got[0].Doc != "Package p is the one worth reading." {
		t.Errorf("packagesIn() = %+v", got)
	}
}

// A copyright notice above the package clause is not a description of the
// package, and go/doc already knows that.
func TestPackagesInOnADocCommentThatSaysNothing(t *testing.T) {
	fsys := fstest.MapFS{
		"p/a.go": {Data: []byte("// Copyright the authors.\npackage p\n")},
		"p/b.go": {Data: []byte("// Package p does a thing.\npackage p\n")},
	}
	got := packagesIn(fsys, nil)
	if len(got) != 1 || got[0].Doc != "Package p does a thing." {
		t.Errorf("packagesIn() = %+v", got)
	}
}

func TestPackagesInOnAFileItCannotRead(t *testing.T) {
	dir := t.TempDir()
	name := filepath.Join(dir, "a.go")
	add(t, name, "// Package p is here.\npackage p\n")
	shut(t, name, 0)

	if got := packagesIn(os.DirFS(dir), nil); len(got) != 0 {
		t.Errorf("packagesIn() = %+v, want nothing", got)
	}
}

func TestCommandBlock(t *testing.T) {
	got := commandBlock(
		[]pkgInfo{{Dir: ".", Name: "main"}, {Dir: "cmd/hello", Name: "main"}},
		[]string{"tools/bot"},
	)
	for _, want := range []string{
		"go run .\n",
		"go run ./cmd/hello\n",
		"go -C tools/bot test ./...  # a module of its own\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the block does not contain %q:\n%s", want, got)
		}
	}
}

func TestLayoutTableStopsWhenItHasSaidEnough(t *testing.T) {
	pkgs := make([]pkgInfo, mostRows+2)
	for i := range pkgs {
		pkgs[i] = pkgInfo{Dir: "p" + strconv.Itoa(i), Name: "p"}
	}

	got := layoutTable(pkgs)
	if !strings.Contains(got, "| p0 ") {
		t.Error("the table does not start where it should")
	}
	if strings.Contains(got, "| p"+strconv.Itoa(mostRows)+" ") {
		t.Errorf("the table has more than %d rows:\n%s", mostRows, got)
	}
	if want := "And 2 more packages, left out"; !strings.Contains(got, want) {
		t.Errorf("the table does not say what it left out:\n%s", got)
	}
}

func TestMdTable(t *testing.T) {
	got := mdTable([]string{"Name", "What it is"}, [][]string{
		{"a", "the first one"},
		{"bb", ""},
	})
	want := strings.Join([]string{
		"| Name | What it is    |",
		"| ---- | ------------- |",
		"| a    | the first one |",
		"| bb   | -             |",
		"",
	}, "\n")
	if got != want {
		t.Errorf("mdTable() =\n%s\nwant\n%s", got, want)
	}
}

func TestGeneratedRows(t *testing.T) {
	got := generatedRows([]generated{
		{By: "mizu gen agents v1", Files: []string{agentsFile}},
		{By: "protoc-gen-go", Files: []string{"rpc/a.pb.go"}},
		{By: "an older mizu", Files: []string{agentsFile}},
	})
	want := [][]string{
		{"mizu gen agents v1", agentsFile},
		{"protoc-gen-go", "rpc/a.pb.go"},
	}
	if fmt.Sprint(got) != fmt.Sprint(want) {
		t.Errorf("generatedRows() = %v, want %v", got, want)
	}
}
