version: "2"
linters:
  default: all
  disable:
    # Whitespace style - too opinionated
    - wsl
    - wsl_v5
    # Variable name length - short names like c, r, w are idiomatic in Go HTTP handlers
    - varnamelen
    # Magic numbers - HTTP status codes and buffer sizes are fine inline
    - mnd
    # Exhaustive struct - default values are intentional
    - exhaustruct
    # Test package separation - same package tests are valid
    - testpackage
    # Parallel tests - not always appropriate
    - paralleltest
    # Function ordering - stylistic preference
    - funcorder
    # Global variables - sentinel errors and defaults are valid
    - gochecknoglobals
    # init functions - sometimes needed
    - gochecknoinits
    # Named returns - can be useful for documentation
    - nonamedreturns
    # Newline before return - stylistic
    - nlreturn
    # No inline error - stylistic
    - noinlineerr
    # Interface returns - sometimes appropriate
    - ireturn
    # Nil/nil returns - sometimes appropriate
    - nilnil
    # Prealloc - minor optimization, often noisy
    - prealloc
    # Revive unexported return - internal types are fine
    - revive
    # Tag alignment - stylistic
    - tagalign
    # JSON tag naming - existing convention
    - tagliatelle
    # Duplicate code - test code often has similar structure
    - dupl
    # Line length - can be too restrictive
    - lll
    # Cognitive complexity - often false positives for switch statements
    - gocognit
    # Cyclomatic complexity via gocyclo - cyclop is enough
    - gocyclo
    # Perfsprint - micro-optimization
    - perfsprint
    # Mirror - rarely useful
    - mirror
    # Sloglint - too strict
    - sloglint
    # Godot - comment formatting
    - godot
    # Godoclint - documentation style
    - godoclint
    # Predeclared - rare issue
    - predeclared
    # Dupword - rarely useful
    - dupword
    # Use testing - too strict
    - usetesting
    # Intrange - minor style
    - intrange
    # Musttag - struct tags are optional
    - musttag
    # Unparam - unused params sometimes needed for interface compliance
    - unparam
    # Wasted assign - can have false positives
    - wastedassign
    # Embedded struct check - stylistic
    - embeddedstructfieldcheck
    # Context check - too many false positives for HTTP server contexts
    - contextcheck
    # HTTP requests without context - middlewares create their own
    - noctx
    # Error wrapping - internal packages don't need to wrap
    - wrapcheck
    # Use stdlib vars - minor style
    - usestdlibvars
    # Exhaustive switch - not always needed
    - exhaustive
    # Modernize - can break compatibility
    - modernize
    # Nil error return - sometimes valid
    - nilerr
    # Error definitions - too strict
    - err113
    # Errchkjson - too noisy
    - errchkjson
    # Forbidigo - disabled
    - forbidigo
    # Cyclop - disabled due to middleware complexity
    - cyclop
    # Funlen - disabled for middlewares
    - funlen
    # Nestif - disabled
    - nestif
    # Goconst - too many false positives
    - goconst
    # Gocritic - too strict
    - gocritic
    # Force type assert - in tests are fine
    - forcetypeassert
    # Depguard - not needed
    - depguard
    # Gosec - many false positives for web framework
    - gosec
    # Staticcheck - keep but exclude specific
    # - staticcheck

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - err113
        - goconst
        - funlen
        - forcetypeassert
        - errchkjson
        - nestif
        - gocritic
    # Exclude known patterns
    - path: middlewares/
      linters:
        - cyclop