name = "translate"
main = "worker/index.ts"
compatibility_date = "2026-02-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[kv_namespaces]]
binding = "TRANSLATE_CACHE"
id = "3ad770f50e95400d94b5bddf6fd5ab11"

[browser]
binding = "BROWSER"

[[queues.producers]]
queue = "translate-tasks"
binding = "TRANSLATE_QUEUE"

[[queues.consumers]]
queue = "translate-tasks"
max_batch_size = 10
max_batch_timeout = 5

[vars]
ENVIRONMENT = "production"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "translate_events"
