import { icons, cardIcon } from '../icons'

export const dataFormatsPage = `
<h2>Data Formats</h2>
<p>OpenIndex works with several data formats. Some come from Common Crawl (WARC, WAT, WET), others are generated by our tools (Parquet indexes, DuckDB shards).</p>

<table>
  <thead>
    <tr>
      <th>Format</th>
      <th>Source</th>
      <th>Use Case</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>WARC</strong></td>
      <td>Common Crawl</td>
      <td>Full HTTP responses (headers + body)</td>
    </tr>
    <tr>
      <td><strong>WAT</strong></td>
      <td>Common Crawl</td>
      <td>Extracted metadata as JSON</td>
    </tr>
    <tr>
      <td><strong>WET</strong></td>
      <td>Common Crawl</td>
      <td>Plaintext extraction</td>
    </tr>
    <tr>
      <td><strong>Parquet</strong></td>
      <td>Common Crawl / OpenIndex</td>
      <td>Columnar index for SQL queries</td>
    </tr>
    <tr>
      <td><strong>DuckDB</strong></td>
      <td>OpenIndex</td>
      <td>Sharded result database from crawls</td>
    </tr>
  </tbody>
</table>

<hr>

<h2>WARC (Web ARChive)</h2>
<p>The standard format for web archives, defined by <a href="https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/">ISO 28500</a>. Each file contains complete HTTP request/response pairs. Common Crawl WARC files are gzip-compressed, typically ~1 GB each.</p>

<pre><code>WARC/1.0
WARC-Type: response
WARC-Date: 2026-01-15T08:30:00Z
WARC-Target-URI: https://example.com/page
Content-Type: application/http;msgtype=response
Content-Length: 12847

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

&lt;!DOCTYPE html&gt;
&lt;html&gt;...&lt;/html&gt;</code></pre>

<p>Record types: <code>warcinfo</code> (file metadata), <code>request</code> (HTTP request), <code>response</code> (HTTP response), <code>metadata</code> (crawl annotations), <code>revisit</code> (deduplication pointer).</p>

<hr>

<h2>WAT (Web Archive Transformation)</h2>
<p>JSON Lines format with extracted metadata from each WARC record. Includes HTTP headers, HTML meta tags, detected links, and language. Smaller than WARC files -- useful when you need metadata without full HTML.</p>

<pre><code>{
  "Envelope": {
    "WARC-Header-Metadata": {
      "WARC-Target-URI": "https://example.com/page",
      "WARC-Date": "2026-01-15T08:30:00Z"
    },
    "Payload-Metadata": {
      "HTTP-Response-Metadata": {
        "Response-Message": { "Status": 200 },
        "Headers": { "Content-Type": "text/html" }
      },
      "HTML-Metadata": {
        "Head": { "Title": "Example Page" },
        "Links": [{"url": "/about", "text": "About"}]
      }
    }
  }
}</code></pre>

<hr>

<h2>WET (WARC Encapsulated Text)</h2>
<p>Clean plaintext extracted from each page. Boilerplate, navigation, and ads removed. Used for NLP and text analysis.</p>

<pre><code>WARC/1.0
WARC-Type: conversion
WARC-Target-URI: https://example.com/page
Content-Type: text/plain
Content-Length: 1847

Example Page Title

This is the extracted body text from the page.
Navigation, headers, and ads have been removed.</code></pre>

<hr>

<h2>Parquet (Columnar Index)</h2>
<p>Common Crawl publishes a columnar index in Apache Parquet format. This is the primary way to query the crawl at scale -- you can filter by domain, language, status code, etc. without downloading WARC files.</p>

<h3>CC Index Schema</h3>
<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr><td><code>url</code></td><td>STRING</td><td>Full URL</td></tr>
    <tr><td><code>url_host_name</code></td><td>STRING</td><td>Hostname (e.g., www.example.com)</td></tr>
    <tr><td><code>url_host_registered_domain</code></td><td>STRING</td><td>Registered domain (e.g., example.com)</td></tr>
    <tr><td><code>url_host_tld</code></td><td>STRING</td><td>Top-level domain</td></tr>
    <tr><td><code>content_languages</code></td><td>STRING</td><td>Detected languages</td></tr>
    <tr><td><code>content_mime_type</code></td><td>STRING</td><td>MIME type</td></tr>
    <tr><td><code>fetch_status</code></td><td>INT32</td><td>HTTP status code</td></tr>
    <tr><td><code>fetch_time</code></td><td>TIMESTAMP</td><td>Crawl timestamp</td></tr>
    <tr><td><code>warc_filename</code></td><td>STRING</td><td>WARC file containing this record</td></tr>
    <tr><td><code>warc_record_offset</code></td><td>INT64</td><td>Byte offset in WARC file</td></tr>
    <tr><td><code>warc_record_length</code></td><td>INT64</td><td>Record length in bytes</td></tr>
    <tr><td><code>content_digest</code></td><td>STRING</td><td>Content hash for deduplication</td></tr>
  </tbody>
</table>

<h3>Example Queries</h3>
<pre><code># Count pages by TLD (remote query, zero download)
duckdb -c "
INSTALL httpfs; LOAD httpfs;
SELECT url_host_tld, COUNT(*) as pages
FROM read_parquet('s3://commoncrawl/cc-index/table/cc-main/warc/crawl=CC-MAIN-2026-04/subset=warc/*.parquet')
GROUP BY url_host_tld
ORDER BY pages DESC
LIMIT 20;
"

# Find all pages for a domain
SELECT url, fetch_status, content_languages
FROM read_parquet('*.parquet')
WHERE url_host_registered_domain = 'example.com'
  AND fetch_status = 200
LIMIT 100;</code></pre>

<hr>

<h2>DuckDB (Sharded Results)</h2>
<p>OpenIndex tools store crawl results in sharded DuckDB databases. The recrawler uses 16 shards for concurrent writes; the domain crawler uses 8.</p>

<h3>Recrawler ResultDB Schema</h3>
<p>Stored at <code>$HOME/data/common-crawl/{CrawlID}/recrawl/</code> in 16 shards:</p>

<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr><td><code>url</code></td><td>VARCHAR</td><td>Original URL from CC index</td></tr>
    <tr><td><code>status</code></td><td>INTEGER</td><td>HTTP status code (0 = failed)</td></tr>
    <tr><td><code>content_type</code></td><td>VARCHAR</td><td>Response Content-Type</td></tr>
    <tr><td><code>content_length</code></td><td>INTEGER</td><td>Response body size</td></tr>
    <tr><td><code>redirect_url</code></td><td>VARCHAR</td><td>Redirect target (if 3xx)</td></tr>
    <tr><td><code>error</code></td><td>VARCHAR</td><td>Error message (if failed)</td></tr>
    <tr><td><code>duration_ms</code></td><td>INTEGER</td><td>Request duration</td></tr>
    <tr><td><code>fetched_at</code></td><td>TIMESTAMP</td><td>Fetch timestamp</td></tr>
  </tbody>
</table>

<h3>Domain Crawler ResultDB Schema</h3>
<p>Stored at <code>$HOME/data/crawler/{domain}/results/</code> in 8 shards:</p>

<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr><td><code>url</code></td><td>VARCHAR</td><td>Page URL</td></tr>
    <tr><td><code>status</code></td><td>INTEGER</td><td>HTTP status code</td></tr>
    <tr><td><code>content_type</code></td><td>VARCHAR</td><td>MIME type</td></tr>
    <tr><td><code>content_length</code></td><td>INTEGER</td><td>Body size</td></tr>
    <tr><td><code>title</code></td><td>VARCHAR</td><td>Extracted page title</td></tr>
    <tr><td><code>links_count</code></td><td>INTEGER</td><td>Number of outbound links</td></tr>
    <tr><td><code>fetched_at</code></td><td>TIMESTAMP</td><td>Fetch timestamp</td></tr>
  </tbody>
</table>

<h3>Querying Sharded Results</h3>
<pre><code># Query all shards at once with DuckDB glob
duckdb -c "
SELECT status, COUNT(*) as cnt
FROM read_parquet('~/data/common-crawl/CC-MAIN-2026-04/recrawl/*.duckdb')
-- Note: for DuckDB files, open each and UNION or use the CLI
"

# Or open a single shard
duckdb ~/data/common-crawl/CC-MAIN-2026-04/recrawl/results_00.duckdb -c "
SELECT status, COUNT(*) as cnt FROM results GROUP BY status ORDER BY cnt DESC;
"</code></pre>

<div class="note">
  DuckDB files can be opened directly with the <code>duckdb</code> CLI or any DuckDB client library. Each shard is a standalone database.
</div>
`
