import { icons, cardIcon } from '../icons'

export const faqPage = `
<h2>Frequently Asked Questions</h2>

<h3>General</h3>

<details>
  <summary>What is OpenIndex?</summary>
  <div class="details-body">
    <p>OpenIndex is a new open-source project for crawling, indexing, and querying web data. It provides CLI tools for working with Common Crawl archives, a high-throughput web recrawler, a domain crawler, and a Cloudflare Worker for browsing crawl data. The project started in February 2026 and is under active development.</p>
  </div>
</details>

<details>
  <summary>How is it different from Common Crawl?</summary>
  <div class="details-body">
    <p>OpenIndex builds <strong>on top of</strong> Common Crawl, not as a replacement. Common Crawl provides the raw web archive data (WARC, WAT, WET, Parquet index). OpenIndex provides tools to work with that data: a CLI for downloading and querying CC indexes, a recrawler for checking URL freshness, a domain crawler for targeted crawling, and (eventually) higher-level indexes like full-text search.</p>
    <p>Think of it as tooling and intelligence layers on top of CC's raw data.</p>
  </div>
</details>

<details>
  <summary>Is it free?</summary>
  <div class="details-body">
    <p>Yes. All code is open source under the Apache License 2.0. Common Crawl data is freely available on S3. There are no paid tiers, no API keys, and no rate limiting at this stage.</p>
  </div>
</details>

<details>
  <summary>What is the current status?</summary>
  <div class="details-body">
    <p>Early stage, actively building. The following is working today:</p>
    <ul>
      <li>CLI for Common Crawl index queries, downloads, and WARC fetching</li>
      <li>High-throughput recrawler (Go) with sharded DNS and per-domain limiting</li>
      <li>Experimental recrawler in Zig (raw TCP + TLS)</li>
      <li>Single-domain crawler with HTTP/2 multiplexing</li>
      <li>CC site extraction (CDX + WARC + link extraction)</li>
      <li>CC Viewer Cloudflare Worker (web UI + API)</li>
    </ul>
    <p>Not yet built: full-text search index, vector embeddings, knowledge graph, OQL query language, public API with auth/rate limits.</p>
  </div>
</details>

<details>
  <summary>What languages is it built with?</summary>
  <div class="details-body">
    <p><strong>Go</strong> for the CLI, crawlers, and data processing. <strong>TypeScript</strong> (Hono framework) for Cloudflare Workers. <strong>Zig</strong> for the experimental recrawler. <strong>DuckDB</strong> and <strong>Parquet</strong> for data storage and querying. <strong>React + Vite</strong> for the search frontend.</p>
  </div>
</details>

<h3>Technical</h3>

<details>
  <summary>How does the recrawler work?</summary>
  <div class="details-body">
    <p>The recrawler takes URLs from Common Crawl Parquet index files and checks if they are still reachable. Architecture:</p>
    <ol>
      <li><strong>Batch DNS</strong> -- 20K workers resolve domains, building a DNS cache and dead domain list.</li>
      <li><strong>Streaming probe</strong> -- 5K workers probe domains with TCP connections, immediately feeding reachable URLs to the next stage.</li>
      <li><strong>HTTP fetch</strong> -- 50K workers fetch URLs with per-domain connection limits (default: 8 max conns/domain).</li>
    </ol>
    <p>Results are written to 16-shard DuckDB databases using batch-VALUES inserts (500 rows per statement). DNS cache is persisted for reuse across runs.</p>
  </div>
</details>

<details>
  <summary>How does the domain crawler work?</summary>
  <div class="details-body">
    <p>Single-domain crawler using HTTP/2 multiplexing for high throughput. Uses an errgroup worker pool with a coordinator goroutine and a bloom filter frontier for deduplication. Results are stored in sharded DuckDB (8 shards). Can be paused and resumed. Benchmarked at 275 pages/s peak on kenh14.vn (1380 pages in 7 seconds).</p>
  </div>
</details>

<details>
  <summary>What data formats does OpenIndex use?</summary>
  <div class="details-body">
    <p>From Common Crawl: WARC (full HTTP responses), WAT (metadata as JSON), WET (plaintext), Parquet (columnar index). Generated by OpenIndex: sharded DuckDB files for crawl results, DNS cache, and site extraction data. See the <a href="/data-formats">Data Formats</a> page for schemas.</p>
  </div>
</details>

<details>
  <summary>How do I query Common Crawl data?</summary>
  <div class="details-body">
    <p>Three ways:</p>
    <ul>
      <li><strong>CLI:</strong> <code>search cc query --remote --sql "SELECT ..."</code> queries CC Parquet on S3 directly via DuckDB httpfs.</li>
      <li><strong>DuckDB directly:</strong> <code>duckdb -c "INSTALL httpfs; LOAD httpfs; SELECT ... FROM read_parquet('s3://commoncrawl/...')"</code></li>
      <li><strong>CDX API:</strong> <code>search cc url https://example.com</code> queries the CC CDX API (zero disk, zero download).</li>
    </ul>
  </div>
</details>

<details>
  <summary>Can I contribute?</summary>
  <div class="details-body">
    <p>Yes. The project is open source and open for contributions. Start at the <a href="https://github.com/nicholasgasior/gopher-crawl">GitHub repository</a>. Good first areas: improving the CC Viewer worker, adding new CLI commands, writing tests, or working on the OQL query language design.</p>
  </div>
</details>

<details>
  <summary>What license is the code under?</summary>
  <div class="details-body">
    <p>Apache License 2.0. You can use, modify, and distribute the code for any purpose, including commercial use.</p>
  </div>
</details>
`
