// Package sdkpy generates a modern Python SDK from contract.Service.
package sdkpy

import (
	"bytes"
	"embed"
	"fmt"
	"path"
	"sort"
	"strings"
	"text/template"
	"unicode"

	contract "github.com/go-mizu/mizu/contract/v2"
	"github.com/go-mizu/mizu/contract/v2/sdk"
)

// IMPORTANT: repo currently has only templates/*.tmpl (no subfolders).
//
//go:embed templates/*.tmpl
var templateFS embed.FS

// Config controls Python SDK generation.
type Config struct {
	// Package is the Python import package name (top-level module).
	// Default: sanitized lowercase service name, or "sdk".
	Package string

	// Version is the package version written to pyproject.toml.
	// Default: "0.0.0".
	Version string
}

// Generate produces a set of files for a Python SDK.
// Output is a uv-friendly project with src/ layout (as implemented by templates).
func Generate(svc *contract.Service, cfg *Config) ([]*sdk.File, error) {
	if svc == nil {
		return nil, fmt.Errorf("sdkpy: nil service")
	}

	m, err := buildModel(svc, cfg)
	if err != nil {
		return nil, err
	}

	tpl := template.New("sdkpy").Funcs(template.FuncMap{
		"pyQuote": pyQuote,
		"pyIdent": pyIdent,
		"snake":   toSnake,
		"pascal":  toPascal,
		"join":    strings.Join,
		"trim":    strings.TrimSpace,
		"lower":   strings.ToLower,
		"indent":  indent,
	})

	// Parse only templates we actually need.
	// This intentionally excludes README.md.tmpl to keep E2E stable and minimal.
	need := []string{
		"templates/pyproject.toml.tmpl",
		"templates/_client.py.tmpl",
		"templates/_types.py.tmpl",
		"templates/_streaming.py.tmpl",
		"templates/_resource.py.tmpl",
	}
	var errParse error
	tpl, errParse = tpl.ParseFS(templateFS, need...)
	if errParse != nil {
		return nil, fmt.Errorf("sdkpy: parse templates: %w", errParse)
	}

	// Provide a tiny inline template for __init__.py to avoid adding another file on disk.
	if _, err := tpl.New("__init__.py.inline.tmpl").Parse(initTemplate); err != nil {
		return nil, fmt.Errorf("sdkpy: parse inline __init__.py template: %w", err)
	}

	outPlan := []struct {
		Path string
		Tpl  string
	}{
		{Path: "pyproject.toml", Tpl: "templates/pyproject.toml.tmpl"},

		{Path: "src/" + m.Package + "/_client.py", Tpl: "templates/_client.py.tmpl"},
		{Path: "src/" + m.Package + "/_types.py", Tpl: "templates/_types.py.tmpl"},
		{Path: "src/" + m.Package + "/_streaming.py", Tpl: "templates/_streaming.py.tmpl"},
		{Path: "src/" + m.Package + "/_resource.py", Tpl: "templates/_resource.py.tmpl"},

		{Path: "src/" + m.Package + "/__init__.py", Tpl: "__init__.py.inline.tmpl"},
	}

	var files []*sdk.File
	for _, item := range outPlan {
		var buf bytes.Buffer
		if err := tpl.ExecuteTemplate(&buf, item.Tpl, m); err != nil {
			return nil, fmt.Errorf("sdkpy: execute template %s: %w", item.Tpl, err)
		}
		files = append(files, &sdk.File{
			Path:    path.Clean(item.Path),
			Content: buf.String(),
		})
	}

	return files, nil
}

const initTemplate = `# Code generated by sdkpy. DO NOT EDIT.

from ._client import OpenAI, AsyncOpenAI

__all__ = ["OpenAI", "AsyncOpenAI"]
`

type model struct {
	Package string
	Version string

	Service struct {
		Name        string
		Sanitized   string
		Description string
	}

	Defaults struct {
		BaseURL string
		Auth    string
		Headers []kv
	}

	Types     []typeModel
	Resources []resourceModel

	HasSSE bool
}

type kv struct {
	K string
	V string
}

type typeModel struct {
	Name        string
	Description string
	Kind        contract.TypeKind

	Fields   []fieldModel
	Elem     string
	Tag      string
	Variants []variantModel
}

type fieldModel struct {
	Name        string
	PyName      string
	Description string
	PyType      string

	Optional bool
	Nullable bool
	Enum     []string
	Const    string
}

type variantModel struct {
	Value       string
	Type        string
	Description string
	FieldName   string
}

type resourceModel struct {
	Name        string
	PyName      string
	Description string
	Methods     []methodModel
}

type methodModel struct {
	Name        string
	PyName      string
	Description string

	HasInput  bool
	HasOutput bool

	InputType  string
	OutputType string

	HTTPMethod string
	HTTPPath   string

	IsStreaming    bool
	StreamMode     string
	StreamIsSSE    bool
	StreamItemType string
}

func buildModel(svc *contract.Service, cfg *Config) (*model, error) {
	m := &model{}

	if cfg != nil && strings.TrimSpace(cfg.Package) != "" {
		m.Package = pyIdent(cfg.Package)
	} else {
		p := strings.ToLower(sanitizeIdent(svc.Name))
		if p == "" {
			p = "sdk"
		}
		m.Package = pyIdent(p)
	}

	if cfg != nil && strings.TrimSpace(cfg.Version) != "" {
		m.Version = strings.TrimSpace(cfg.Version)
	} else {
		m.Version = "0.0.0"
	}

	m.Service.Name = svc.Name
	m.Service.Sanitized = sanitizeIdent(svc.Name)
	m.Service.Description = svc.Description

	if svc.Defaults != nil {
		m.Defaults.BaseURL = strings.TrimRight(strings.TrimSpace(svc.Defaults.BaseURL), "/")
		m.Defaults.Auth = strings.TrimSpace(svc.Defaults.Auth)

		if len(svc.Defaults.Headers) > 0 {
			keys := make([]string, 0, len(svc.Defaults.Headers))
			for k := range svc.Defaults.Headers {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				m.Defaults.Headers = append(m.Defaults.Headers, kv{K: k, V: svc.Defaults.Headers[k]})
			}
		}
	}

	typeByName := map[string]*contract.Type{}
	for _, t := range svc.Types {
		if t != nil && strings.TrimSpace(t.Name) != "" {
			typeByName[t.Name] = t
		}
	}

	m.HasSSE = hasSSE(svc)

	typeNames := make([]string, 0, len(typeByName))
	for name := range typeByName {
		typeNames = append(typeNames, name)
	}
	sort.Strings(typeNames)

	for _, name := range typeNames {
		t := typeByName[name]
		if t == nil {
			continue
		}
		tm := typeModel{
			Name:        t.Name,
			Description: t.Description,
			Kind:        t.Kind,
			Elem:        string(t.Elem),
			Tag:         t.Tag,
		}

		switch t.Kind {
		case contract.KindStruct:
			for _, f := range t.Fields {
				tm.Fields = append(tm.Fields, fieldModel{
					Name:        f.Name,
					PyName:      toSnake(f.Name),
					Description: f.Description,
					PyType:      pyType(typeByName, f.Type, f.Optional, f.Nullable),
					Optional:    f.Optional,
					Nullable:    f.Nullable,
					Enum:        append([]string(nil), f.Enum...),
					Const:       f.Const,
				})
			}

		case contract.KindSlice:
			tm.Elem = pyType(typeByName, t.Elem, false, false)

		case contract.KindMap:
			tm.Elem = pyType(typeByName, t.Elem, false, false)

		case contract.KindUnion:
			for _, v := range t.Variants {
				tm.Variants = append(tm.Variants, variantModel{
					Value:       v.Value,
					Type:        string(v.Type),
					Description: v.Description,
					FieldName:   toPascal(string(v.Type)),
				})
			}
		}

		m.Types = append(m.Types, tm)
	}

	for _, r := range svc.Resources {
		if r == nil {
			continue
		}
		rm := resourceModel{
			Name:        r.Name,
			PyName:      toSnake(r.Name),
			Description: r.Description,
		}

		for _, mm := range r.Methods {
			if mm == nil {
				continue
			}

			httpMethod := "POST"
			httpPath := "/" + r.Name + "/" + mm.Name
			if mm.HTTP != nil {
				if strings.TrimSpace(mm.HTTP.Method) != "" {
					httpMethod = strings.ToUpper(mm.HTTP.Method)
				}
				if strings.TrimSpace(mm.HTTP.Path) != "" {
					httpPath = mm.HTTP.Path
				}
			}

			hasInput := strings.TrimSpace(string(mm.Input)) != ""
			hasOutput := strings.TrimSpace(string(mm.Output)) != ""

			isStreaming := mm.Stream != nil
			streamMode := ""
			streamIsSSE := false
			streamItem := ""

			if isStreaming {
				streamMode = strings.TrimSpace(mm.Stream.Mode)
				streamIsSSE = streamMode == "" || strings.EqualFold(streamMode, "sse")
				streamItem = strings.TrimSpace(string(mm.Stream.Item))
			}

			rm.Methods = append(rm.Methods, methodModel{
				Name:        mm.Name,
				PyName:      toSnake(mm.Name),
				Description: mm.Description,

				HasInput:   hasInput,
				HasOutput:  hasOutput,
				InputType:  string(mm.Input),
				OutputType: string(mm.Output),

				HTTPMethod: httpMethod,
				HTTPPath:   httpPath,

				IsStreaming:    isStreaming,
				StreamMode:     streamMode,
				StreamIsSSE:    streamIsSSE,
				StreamItemType: streamItem,
			})
		}

		m.Resources = append(m.Resources, rm)
	}

	return m, nil
}

func hasSSE(svc *contract.Service) bool {
	for _, r := range svc.Resources {
		if r == nil {
			continue
		}
		for _, m := range r.Methods {
			if m == nil || m.Stream == nil {
				continue
			}
			mode := strings.TrimSpace(m.Stream.Mode)
			if mode == "" || strings.EqualFold(mode, "sse") {
				return true
			}
		}
	}
	return false
}

func pyType(typeByName map[string]*contract.Type, ref contract.TypeRef, optional, nullable bool) string {
	r := strings.TrimSpace(string(ref))
	if r == "" {
		return "object"
	}

	base := basePyType(typeByName, r)
	if optional || nullable {
		if !strings.HasPrefix(base, "Optional[") {
			return "Optional[" + base + "]"
		}
	}
	return base
}

func basePyType(typeByName map[string]*contract.Type, r string) string {
	if _, ok := typeByName[r]; ok {
		return toPascal(r)
	}

	switch r {
	case "string":
		return "str"
	case "bool", "boolean":
		return "bool"
	case "int", "int32", "int64", "uint", "uint32", "uint64":
		return "int"
	case "float32", "float64":
		return "float"
	case "time.Time":
		return "datetime"
	case "json.RawMessage", "any", "interface{}":
		return "object"
	}

	if strings.HasPrefix(r, "[]") {
		elem := strings.TrimSpace(strings.TrimPrefix(r, "[]"))
		return "List[" + basePyType(typeByName, elem) + "]"
	}
	if strings.HasPrefix(r, "map[string]") {
		elem := strings.TrimSpace(strings.TrimPrefix(r, "map[string]"))
		return "Dict[str, " + basePyType(typeByName, elem) + "]"
	}

	return "object"
}

func pyQuote(s string) string { return fmt.Sprintf("%q", s) }

func pyIdent(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "sdk"
	}
	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "sdk"
	}
	r0 := rune(out[0])
	if !(unicode.IsLetter(r0) || r0 == '_') {
		out = "_" + out
	}
	return out
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func toSnake(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	var b strings.Builder
	var prevLower bool
	for _, r := range s {
		if r == '-' || r == '.' || r == ' ' {
			r = '_'
		}
		if r == '_' {
			if b.Len() > 0 && b.String()[b.Len()-1] != '_' {
				b.WriteByte('_')
			}
			prevLower = false
			continue
		}
		if unicode.IsUpper(r) {
			if prevLower {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			prevLower = false
			continue
		}
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
			prevLower = unicode.IsLetter(r) && unicode.IsLower(r)
			continue
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "x"
	}
	return out
}

func toPascal(s string) string {
	if s == "" {
		return ""
	}
	var b strings.Builder
	capNext := true
	for _, r := range s {
		if r == '_' || r == '-' || r == '.' || r == ' ' {
			capNext = true
			continue
		}
		if capNext {
			b.WriteRune(unicode.ToUpper(r))
			capNext = false
		} else {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "X"
	}
	out = strings.ReplaceAll(out, "Id", "ID")
	out = strings.ReplaceAll(out, "Url", "URL")
	out = strings.ReplaceAll(out, "Http", "HTTP")
	out = strings.ReplaceAll(out, "Api", "API")
	out = strings.ReplaceAll(out, "Json", "JSON")
	out = strings.ReplaceAll(out, "Sse", "SSE")
	return out
}

func indent(n int, s string) string {
	if n <= 0 || s == "" {
		return s
	}
	pad := strings.Repeat(" ", n)
	lines := strings.Split(s, "\n")
	for i := range lines {
		if strings.TrimSpace(lines[i]) == "" {
			continue
		}
		lines[i] = pad + lines[i]
	}
	return strings.Join(lines, "\n")
}
