const fs = require('fs')
const path = require('path')

const postsDir = path.join(__dirname, '../src/content/posts')
const outFile = path.join(__dirname, '../src/posts-manifest.ts')

const files = fs
  .readdirSync(postsDir)
  .filter((f) => f.endsWith('.md'))
  .sort()

const imports = files.map((f, i) => `import post${i} from './content/posts/${f}'`).join('\n')
const array = files.map((_, i) => `post${i}`).join(', ')

const output = `// AUTO-GENERATED by scripts/gen-posts.js — do not edit
${imports}

export const postFiles: string[] = [${array}]
`

fs.writeFileSync(outFile, output)
console.log(`Generated ${outFile} with ${files.length} posts`)
