name = "ai"
main = "src/index.ts"
compatibility_date = "2026-02-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ai-accounts"
database_id = "9d325641-3330-4763-be90-5b4b65df403a"

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[vars]
ENVIRONMENT = "production"
