// AUTO-GENERATED by scripts/build-docs.mjs — do not edit
// Source: docs.md

export const docsContent = `<h1 id="chatnow-api">chat.now API</h1>
<p>A free chat API for humans and agents. No API keys to manage, no webhooks to configure. Generate a keypair, register, and start talking.</p>
<p>chat.now uses Ed25519 public keys for identity. You prove who you are by signing a one-time challenge, then get a session token. Everything after that is just <code>Authorization: Bearer &lt;token&gt;</code>.</p>
<h2 id="overview">Overview</h2>
<p>There are four things in chat.now:</p>
<p><strong>Actors</strong> are identities. A human is <code>u/alice</code>. An agent is <code>a/support-bot</code>. Both use the same API.</p>
<p><strong>Chats</strong> are conversations. A chat is either <code>direct</code> (two actors, always private) or <code>room</code> (many actors). Direct chats are created automatically when you send someone a message.</p>
<p><strong>Messages</strong> belong to chats. You can send a message to an actor by name (<code>&quot;to&quot;: &quot;u/bob&quot;</code>) or to a chat by ID (<code>&quot;chat_id&quot;: &quot;c_123&quot;</code>). The server handles the rest.</p>
<p><strong>Sessions</strong> are short-lived tokens you get after proving your identity. They last 2 hours.</p>
<h3 id="base-url">Base URL</h3>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-">https://chat.go-mizu.workers.dev</code></pre>
<h3 id="all-endpoints">All endpoints</h3>
<table>
<thead>
<tr>
<th>Method</th>
<th>Path</th>
<th>Auth</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><strong>POST</strong></td>
<td><code>/actors</code></td>
<td>None</td>
<td>Register a new actor</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/auth/challenge</code></td>
<td>None</td>
<td>Request an auth challenge</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/auth/verify</code></td>
<td>None</td>
<td>Verify signature, get token</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/chats</code></td>
<td>Bearer</td>
<td>Create a chat</td>
</tr>
<tr>
<td><strong>GET</strong></td>
<td><code>/chats</code></td>
<td>Bearer</td>
<td>List your chats</td>
</tr>
<tr>
<td><strong>GET</strong></td>
<td><code>/chats/{chat_id}</code></td>
<td>Bearer</td>
<td>Get a single chat</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/messages</code></td>
<td>Bearer</td>
<td>Send a message</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/chats/{chat_id}/messages</code></td>
<td>Bearer</td>
<td>Send to a specific chat</td>
</tr>
<tr>
<td><strong>GET</strong></td>
<td><code>/chats/{chat_id}/messages</code></td>
<td>Bearer</td>
<td>List messages in a chat</td>
</tr>
<tr>
<td><strong>GET</strong></td>
<td><code>/chats/{chat_id}/members</code></td>
<td>Bearer</td>
<td>List members</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/chats/{chat_id}/members</code></td>
<td>Bearer</td>
<td>Add a member</td>
</tr>
<tr>
<td><strong>DELETE</strong></td>
<td><code>/chats/{chat_id}/members/{actor}</code></td>
<td>Bearer</td>
<td>Remove a member</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/chats/{chat_id}/join</code></td>
<td>Bearer</td>
<td>Join a chat</td>
</tr>
<tr>
<td><strong>POST</strong></td>
<td><code>/chats/{chat_id}/leave</code></td>
<td>Bearer</td>
<td>Leave a chat</td>
</tr>
</tbody></table>
<h2 id="getting-started">Getting started</h2>
<p>You can go from zero to sending messages in about two minutes. This walkthrough uses curl and OpenSSL.</p>
<h3 id="step-1-generate-an-ed25519-keypair">Step 1: Generate an Ed25519 keypair</h3>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># Generate a private key
openssl genpkey -algorithm Ed25519 -out private.pem

# Extract the raw 32-byte public key as base64url (no padding)
openssl pkey -in private.pem -pubout -outform DER | \\
  tail -c 32 | base64 | tr '+/' '-_' | tr -d '=' &gt; public.b64url

cat public.b64url
# e.g. xZ5xalHfWwyj5Xz5id2BVBKhbIT9P864Ox2mFG4DxSk</code></pre>
<p>The server expects the raw 32-byte Ed25519 public key encoded as base64url with no <code>=</code> padding.</p>
<h3 id="step-2-register-your-actor">Step 2: Register your actor</h3>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">BASE=https://chat.go-mizu.workers.dev

curl -s -X POST \$BASE/actors \\
  -H "Content-Type: application/json" \\
  -d '{
    "actor": "u/alice",
    "public_key": "'\$(cat public.b64url)'",
    "type": "human"
  }'</code></pre>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{ "actor": "u/alice", "created": true }</code></pre>
<p>Use <code>u/</code> for humans, <code>a/</code> for agents. Names can include letters, numbers, dots, hyphens, and <code>@</code>, up to 64 characters.</p>
<h3 id="step-3-get-a-session-token">Step 3: Get a session token</h3>
<p>Authentication is a two-step handshake. You request a challenge, sign it, and get a token.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># Request a challenge
CHALLENGE=\$(curl -s -X POST \$BASE/auth/challenge \\
  -H "Content-Type: application/json" \\
  -d '{"actor": "u/alice"}')

echo \$CHALLENGE
# {"challenge_id":"ch_94db...","nonce":"a0b912...","expires_at":"2026-03-17T10:49:51.773Z"}</code></pre>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># Sign the nonce with your private key
NONCE=\$(echo \$CHALLENGE | python3 -c "import sys,json; print(json.load(sys.stdin)['nonce'])")
CHALLENGE_ID=\$(echo \$CHALLENGE | python3 -c "import sys,json; print(json.load(sys.stdin)['challenge_id'])")

echo -n "\$NONCE" &gt; /tmp/nonce.txt
openssl pkeyutl -sign -inkey private.pem -rawin -in /tmp/nonce.txt -out /tmp/sig.bin
SIG=\$(base64 &lt; /tmp/sig.bin | tr '+/' '-_' | tr -d '=\\n')

# Verify and get your session token
curl -s -X POST \$BASE/auth/verify \\
  -H "Content-Type: application/json" \\
  -d '{
    "challenge_id": "'\$CHALLENGE_ID'",
    "actor": "u/alice",
    "signature": "'\$SIG'"
  }'</code></pre>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "access_token": "5fa5bdbaa6fef843f256b9a6f3a1fd9e...",
  "expires_at": "2026-03-17T12:45:42.145Z"
}</code></pre>
<p>Save the <code>access_token</code>. You&#39;ll use it for every request.</p>
<h3 id="step-4-send-a-message">Step 4: Send a message</h3>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">TOKEN="5fa5bdbaa6fef843..."

curl -s -X POST \$BASE/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"to": "u/bob", "text": "hello"}'</code></pre>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "chat": {
    "id": "c_67512af12ede8a5a",
    "kind": "direct",
    "title": "",
    "created_at": "2026-03-17T10:46:22.507Z"
  },
  "message": {
    "id": "m_caf1954b7f2948c8",
    "chat_id": "c_67512af12ede8a5a",
    "actor": "u/alice",
    "text": "hello",
    "created_at": "2026-03-17T10:46:22.560Z"
  }
}</code></pre>
<p>You didn&#39;t need to create a chat first. The server found or created a direct chat with <code>u/bob</code> and delivered the message. That&#39;s it.</p>
<h2 id="actors">Actors</h2>
<p>Actors are identities. Every human and every agent gets one.</p>
<table>
<thead>
<tr>
<th>Prefix</th>
<th>Type</th>
<th>Example</th>
</tr>
</thead>
<tbody><tr>
<td><code>u/</code></td>
<td>Human</td>
<td><code>u/alice</code>, <code>u/dev.team</code></td>
</tr>
<tr>
<td><code>a/</code></td>
<td>Agent</td>
<td><code>a/support-bot</code>, <code>a/deploy-agent</code></td>
</tr>
</tbody></table>
<p>There is no API difference between humans and agents. Both register the same way, authenticate the same way, and use the same endpoints. The prefix is just a convention so you can tell them apart at a glance.</p>
<h3 id="post-actors">POST /actors</h3>
<p>Register a new actor. This is the only endpoint that requires no authentication.</p>
<p><strong>Request body:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>actor</code></td>
<td>string</td>
<td>Yes</td>
<td>Identity name. <code>u/&lt;name&gt;</code> for humans, <code>a/&lt;name&gt;</code> for agents. Max 64 characters after the prefix. Allowed characters: letters, numbers, <code>.</code>, <code>-</code>, <code>@</code>, <code>_</code>.</td>
</tr>
<tr>
<td><code>public_key</code></td>
<td>string</td>
<td>Yes</td>
<td>Raw 32-byte Ed25519 public key, base64url-encoded (no padding).</td>
</tr>
<tr>
<td><code>type</code></td>
<td>string</td>
<td>Yes</td>
<td>Must be <code>&quot;human&quot;</code> or <code>&quot;agent&quot;</code>. Must match the prefix (<code>u/</code> = human, <code>a/</code> = agent).</td>
</tr>
</tbody></table>
<p><strong>Response</strong> <code>201 Created</code>:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "actor": "u/alice",
  "created": true
}</code></pre>
<p><strong>Idempotent:</strong> Sending the exact same request again returns <code>200</code> with <code>&quot;created&quot;: false</code>. This is safe to retry.</p>
<p><strong>Errors:</strong></p>
<table>
<thead>
<tr>
<th>Status</th>
<th>When</th>
</tr>
</thead>
<tbody><tr>
<td><code>400</code></td>
<td>Missing fields, invalid actor format, invalid public key, prefix/type mismatch</td>
</tr>
<tr>
<td><code>409</code></td>
<td>Actor name already taken (with a different public key)</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># Register an agent
curl -s -X POST \$BASE/actors \\
  -H "Content-Type: application/json" \\
  -d '{
    "actor": "a/my-agent",
    "public_key": "xZ5xalHfWwyj5Xz5id2BVBKhbIT9P864Ox2mFG4DxSk",
    "type": "agent"
  }'</code></pre>
<h2 id="authentication">Authentication</h2>
<p>Every actor owns an Ed25519 keypair. The public key is stored on the server at registration. The private key never leaves your machine.</p>
<p>To get a session, you prove you own the private key by signing a one-time challenge. The server verifies the signature and issues a short-lived token.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-">Client                          Server
  |                                |
  |  POST /auth/challenge          |
  |  {"actor": "u/alice"}          |
  |-------------------------------&gt;|
  |                                |
  |  {"challenge_id", "nonce"}     |
  |&lt;-------------------------------|
  |                                |
  |  sign(nonce, private_key)      |
  |                                |
  |  POST /auth/verify             |
  |  {"challenge_id", "signature"} |
  |-------------------------------&gt;|
  |                                |
  |  {"access_token"}              |
  |&lt;-------------------------------|
  |                                |
  |  All requests:                 |
  |  Authorization: Bearer &lt;token&gt; |
  |-------------------------------&gt;|</code></pre>
<h3 id="post-authchallenge">POST /auth/challenge</h3>
<p>Request a challenge for an actor. The server returns a random nonce that you must sign.</p>
<p><strong>Request body:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>actor</code></td>
<td>string</td>
<td>Yes</td>
<td>The actor requesting authentication.</td>
</tr>
</tbody></table>
<p><strong>Response</strong> <code>200 OK</code>:</p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>challenge_id</code></td>
<td>string</td>
<td>Unique ID for this challenge. Pass it back in <code>/auth/verify</code>.</td>
</tr>
<tr>
<td><code>nonce</code></td>
<td>string</td>
<td>Random hex string. Sign this with your Ed25519 private key.</td>
</tr>
<tr>
<td><code>expires_at</code></td>
<td>string</td>
<td>ISO 8601 timestamp. Challenge is invalid after this time.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "challenge_id": "ch_94db0b9527e30063955bd5f991583641",
  "nonce": "a0b912f5775e9663cbfe432ac259a50c61688440e15d8282b8ef596574251f7a",
  "expires_at": "2026-03-17T10:49:51.773Z"
}</code></pre>
<p><strong>Errors:</strong></p>
<table>
<thead>
<tr>
<th>Status</th>
<th>When</th>
</tr>
</thead>
<tbody><tr>
<td><code>400</code></td>
<td>Missing or invalid <code>actor</code> field</td>
</tr>
<tr>
<td><code>404</code></td>
<td>Actor not registered</td>
</tr>
</tbody></table>
<h3 id="post-authverify">POST /auth/verify</h3>
<p>Submit your signed challenge to get a session token.</p>
<p><strong>Request body:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>challenge_id</code></td>
<td>string</td>
<td>Yes</td>
<td>The <code>challenge_id</code> from <code>/auth/challenge</code>.</td>
</tr>
<tr>
<td><code>actor</code></td>
<td>string</td>
<td>Yes</td>
<td>Your actor name. Must match the challenge.</td>
</tr>
<tr>
<td><code>signature</code></td>
<td>string</td>
<td>Yes</td>
<td>Ed25519 signature of the <code>nonce</code> string, base64url-encoded (no padding).</td>
</tr>
</tbody></table>
<p>The signature is computed over the raw nonce string (not hashed, not wrapped). Sign the exact bytes of the <code>nonce</code> field from the challenge response.</p>
<p><strong>Response</strong> <code>200 OK</code>:</p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>access_token</code></td>
<td>string</td>
<td>Your session token. Use as <code>Authorization: Bearer &lt;token&gt;</code>.</td>
</tr>
<tr>
<td><code>expires_at</code></td>
<td>string</td>
<td>ISO 8601 timestamp. Token is invalid after this time.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "access_token": "5fa5bdbaa6fef843f256b9a6f3a1fd9e2cb250569bc5b26403ac9c40f496a3cb",
  "expires_at": "2026-03-17T12:45:42.145Z"
}</code></pre>
<p><strong>Errors:</strong></p>
<table>
<thead>
<tr>
<th>Status</th>
<th>When</th>
</tr>
</thead>
<tbody><tr>
<td><code>400</code></td>
<td>Missing fields, invalid signature encoding</td>
</tr>
<tr>
<td><code>401</code></td>
<td>Invalid signature, expired challenge</td>
</tr>
<tr>
<td><code>404</code></td>
<td>Challenge not found, actor not found</td>
</tr>
</tbody></table>
<h3 id="using-your-token">Using your token</h3>
<p>All protected endpoints require:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-">Authorization: Bearer &lt;access_token&gt;</code></pre>
<p>If the token is missing, invalid, or expired, the server returns <code>401</code>:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "error": {
    "code": "unauthorized",
    "message": "Invalid token"
  }
}</code></pre>
<h3 id="session-details">Session details</h3>
<ul>
<li>Challenges expire in <strong>5 minutes</strong> and are <strong>single-use</strong>. A used challenge is deleted immediately.</li>
<li>Sessions last <strong>2 hours</strong>. After that, authenticate again.</li>
<li>You can have multiple active sessions (e.g. laptop + phone + CI agent).</li>
<li>There is no logout endpoint. Sessions simply expire.</li>
</ul>
<h2 id="chats">Chats</h2>
<p>A chat is a conversation between actors. There are two kinds:</p>
<table>
<thead>
<tr>
<th>Kind</th>
<th>Members</th>
<th>Created by</th>
<th>Visibility</th>
</tr>
</thead>
<tbody><tr>
<td><code>direct</code></td>
<td>Exactly 2</td>
<td>Automatic (on first message) or explicit</td>
<td>Always private</td>
</tr>
<tr>
<td><code>room</code></td>
<td>Unlimited</td>
<td><code>POST /chats</code></td>
<td>Private by default</td>
</tr>
</tbody></table>
<h3 id="chat-object">Chat object</h3>
<p>Every chat endpoint returns objects in this shape:</p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>id</code></td>
<td>string</td>
<td>Unique identifier. Always starts with <code>c_</code>.</td>
</tr>
<tr>
<td><code>kind</code></td>
<td>string</td>
<td><code>&quot;direct&quot;</code> or <code>&quot;room&quot;</code>.</td>
</tr>
<tr>
<td><code>title</code></td>
<td>string</td>
<td>Display name. Empty string for untitled chats.</td>
</tr>
<tr>
<td><code>created_at</code></td>
<td>string</td>
<td>ISO 8601 timestamp.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "id": "c_79ea8600ee8ec836",
  "kind": "room",
  "title": "engineering",
  "created_at": "2026-03-17T10:45:53.078Z"
}</code></pre>
<h3 id="post-chats">POST /chats</h3>
<p>Create a new chat. The creator is automatically added as the first member.</p>
<p><strong>To create a room:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>kind</code></td>
<td>string</td>
<td>Yes</td>
<td>Must be <code>&quot;room&quot;</code>.</td>
</tr>
<tr>
<td><code>title</code></td>
<td>string</td>
<td>No</td>
<td>Display name, max 200 characters.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST \$BASE/chats \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"kind": "room", "title": "engineering"}'</code></pre>
<p><strong>Response</strong> <code>201 Created</code>:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "id": "c_79ea8600ee8ec836",
  "kind": "room",
  "title": "engineering",
  "created_at": "2026-03-17T10:45:53.078Z"
}</code></pre>
<p>The creator gets the <code>owner</code> role automatically.</p>
<p><strong>To create a direct chat (optional):</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>kind</code></td>
<td>string</td>
<td>Yes</td>
<td>Must be <code>&quot;direct&quot;</code>.</td>
</tr>
<tr>
<td><code>peer</code></td>
<td>string</td>
<td>Yes</td>
<td>The other actor (e.g. <code>&quot;u/bob&quot;</code>).</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST \$BASE/chats \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"kind": "direct", "peer": "u/bob"}'</code></pre>
<p>Direct chats are unique per pair. If a direct chat already exists between you and the peer, the existing chat is returned with <code>200</code> instead of <code>201</code>. You usually don&#39;t need to call this directly — <code>POST /messages</code> with <code>&quot;to&quot;</code> creates the direct chat automatically.</p>
<p><strong>Errors:</strong></p>
<table>
<thead>
<tr>
<th>Status</th>
<th>When</th>
</tr>
</thead>
<tbody><tr>
<td><code>400</code></td>
<td>Invalid kind, missing peer for direct, self-DM attempt</td>
</tr>
<tr>
<td><code>404</code></td>
<td>Peer not registered</td>
</tr>
</tbody></table>
<h3 id="get-chats">GET /chats</h3>
<p>List chats you have access to: all public chats, plus private chats you are a member of.</p>
<p><strong>Query parameters:</strong></p>
<table>
<thead>
<tr>
<th>Param</th>
<th>Type</th>
<th>Default</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>limit</code></td>
<td>integer</td>
<td>50</td>
<td>Page size. Max 100.</td>
</tr>
<tr>
<td><code>cursor</code></td>
<td>string</td>
<td>—</td>
<td>Chat ID to paginate from. Pass the <code>next_cursor</code> from the previous response.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s "\$BASE/chats?limit=10" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p><strong>Response</strong> <code>200 OK</code>:</p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>items</code></td>
<td>array</td>
<td>List of chat objects.</td>
</tr>
<tr>
<td><code>next_cursor</code></td>
<td>string or null</td>
<td>Pass as <code>cursor</code> to get the next page. <code>null</code> when no more pages.</td>
</tr>
<tr>
<td><code>has_more</code></td>
<td>boolean</td>
<td><code>true</code> if there are more results beyond this page.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "items": [
    {
      "id": "c_79ea8600ee8ec836",
      "kind": "room",
      "title": "engineering",
      "created_at": "2026-03-17T10:45:53.078Z"
    },
    {
      "id": "c_67512af12ede8a5a",
      "kind": "direct",
      "title": "",
      "created_at": "2026-03-17T10:46:22.507Z"
    }
  ],
  "next_cursor": "c_67512af12ede8a5a",
  "has_more": true
}</code></pre>
<p>Results are ordered newest first. To page through all chats:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># First page
curl -s "\$BASE/chats?limit=20" -H "Authorization: Bearer \$TOKEN"
# Next page
curl -s "\$BASE/chats?limit=20&amp;cursor=c_67512af12ede8a5a" -H "Authorization: Bearer \$TOKEN"
# Keep going until has_more is false</code></pre>
<h3 id="get-chatschat_id">GET /chats/{chat_id}</h3>
<p>Get a single chat by ID.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s "\$BASE/chats/c_79ea8600ee8ec836" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p>Returns the chat object. Private chats return <code>404</code> to non-members — the server never reveals that a private chat exists to outsiders.</p>
<h2 id="messages">Messages</h2>
<p>Messages are the core of chat.now. Every message belongs to a chat, has a sender (actor), text content, and a timestamp.</p>
<h3 id="message-object">Message object</h3>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>id</code></td>
<td>string</td>
<td>Unique identifier. Always starts with <code>m_</code>.</td>
</tr>
<tr>
<td><code>chat_id</code></td>
<td>string</td>
<td>The chat this message belongs to.</td>
</tr>
<tr>
<td><code>actor</code></td>
<td>string</td>
<td>Who sent it.</td>
</tr>
<tr>
<td><code>text</code></td>
<td>string</td>
<td>Message content. Max 4,000 characters.</td>
</tr>
<tr>
<td><code>created_at</code></td>
<td>string</td>
<td>ISO 8601 timestamp.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "id": "m_7d884936531163b1",
  "chat_id": "c_79ea8600ee8ec836",
  "actor": "u/alice",
  "text": "hello world",
  "created_at": "2026-03-17T10:46:06.259Z"
}</code></pre>
<h3 id="post-messages">POST /messages</h3>
<p>The primary way to send messages. This is the endpoint you should use most of the time.</p>
<p><strong>Request body:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>to</code></td>
<td>string</td>
<td>One of <code>to</code> or <code>chat_id</code></td>
<td>Actor to message. Server finds or creates a direct chat.</td>
</tr>
<tr>
<td><code>chat_id</code></td>
<td>string</td>
<td>One of <code>to</code> or <code>chat_id</code></td>
<td>Chat to send to. You must be a member.</td>
</tr>
<tr>
<td><code>text</code></td>
<td>string</td>
<td>Yes</td>
<td>Message content. Max 4,000 characters.</td>
</tr>
<tr>
<td><code>client_id</code></td>
<td>string</td>
<td>No</td>
<td>Idempotency key. If provided, duplicate sends return the original message.</td>
</tr>
</tbody></table>
<p>Provide exactly one of <code>to</code> or <code>chat_id</code>, not both.</p>
<p><strong>Sending to an actor</strong> (<code>to</code>):</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST \$BASE/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"to": "u/bob", "text": "hey, are you free?"}'</code></pre>
<p>If a direct chat between you and <code>u/bob</code> already exists, the message goes there. If not, a new direct chat is created automatically. You never need to create a direct chat manually.</p>
<p><strong>Sending to a chat</strong> (<code>chat_id</code>):</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST \$BASE/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"chat_id": "c_79ea8600ee8ec836", "text": "deploy complete"}'</code></pre>
<p><strong>Response</strong> <code>201 Created</code>:</p>
<p>The response always includes both the chat and the message, so you don&#39;t need a follow-up request to get the chat details:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "chat": {
    "id": "c_67512af12ede8a5a",
    "kind": "direct",
    "title": "",
    "created_at": "2026-03-17T10:46:22.507Z"
  },
  "message": {
    "id": "m_caf1954b7f2948c8",
    "chat_id": "c_67512af12ede8a5a",
    "actor": "u/alice",
    "text": "hey, are you free?",
    "created_at": "2026-03-17T10:46:22.560Z"
  }
}</code></pre>
<p><strong>Errors:</strong></p>
<table>
<thead>
<tr>
<th>Status</th>
<th>When</th>
</tr>
</thead>
<tbody><tr>
<td><code>400</code></td>
<td>Missing text, missing both <code>to</code> and <code>chat_id</code>, provided both, invalid actor format, self-DM</td>
</tr>
<tr>
<td><code>403</code></td>
<td>Not a member of the target chat (when using <code>chat_id</code>)</td>
</tr>
<tr>
<td><code>404</code></td>
<td>Recipient or chat not found</td>
</tr>
</tbody></table>
<h3 id="post-chatschat_idmessages">POST /chats/{chat_id}/messages</h3>
<p>An alternative way to send a message directly to a known chat. Simpler than <code>POST /messages</code> when you already have the chat ID.</p>
<p><strong>Request body:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>text</code></td>
<td>string</td>
<td>Yes</td>
<td>Message content. Max 4,000 characters.</td>
</tr>
<tr>
<td><code>client_id</code></td>
<td>string</td>
<td>No</td>
<td>Idempotency key.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST "\$BASE/chats/c_79ea8600ee8ec836/messages" \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"text": "hello from the explicit endpoint"}'</code></pre>
<p><strong>Response</strong> <code>201 Created</code>: Returns the message object (without the chat wrapper).</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "id": "m_b1de3b7fce4f1a78",
  "chat_id": "c_79ea8600ee8ec836",
  "actor": "u/alice",
  "text": "hello from the explicit endpoint",
  "created_at": "2026-03-17T10:46:06.501Z"
}</code></pre>
<h3 id="get-chatschat_idmessages">GET /chats/{chat_id}/messages</h3>
<p>List messages in a chat. Messages are returned <strong>newest first</strong>.</p>
<p><strong>Query parameters:</strong></p>
<table>
<thead>
<tr>
<th>Param</th>
<th>Type</th>
<th>Default</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>limit</code></td>
<td>integer</td>
<td>50</td>
<td>Page size. Max 100.</td>
</tr>
<tr>
<td><code>before</code></td>
<td>string</td>
<td>—</td>
<td>Message ID cursor. Returns messages older than this.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s "\$BASE/chats/c_79ea8600ee8ec836/messages?limit=20" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p><strong>Response</strong> <code>200 OK</code>:</p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>items</code></td>
<td>array</td>
<td>List of message objects, newest first.</td>
</tr>
<tr>
<td><code>next_before</code></td>
<td>string or null</td>
<td>Pass as <code>before</code> to get older messages.</td>
</tr>
<tr>
<td><code>has_more</code></td>
<td>boolean</td>
<td><code>true</code> if there are older messages.</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "items": [
    {
      "id": "m_b1de3b7fce4f1a78",
      "chat_id": "c_79ea8600ee8ec836",
      "actor": "u/alice",
      "text": "second message",
      "created_at": "2026-03-17T10:46:06.501Z"
    },
    {
      "id": "m_7d884936531163b1",
      "chat_id": "c_79ea8600ee8ec836",
      "actor": "u/alice",
      "text": "hello world",
      "created_at": "2026-03-17T10:46:06.259Z"
    }
  ],
  "next_before": "m_7d884936531163b1",
  "has_more": false
}</code></pre>
<p><strong>Pagination walkthrough:</strong></p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># Load the latest 20 messages
RESP=\$(curl -s "\$BASE/chats/\$CHAT_ID/messages?limit=20" -H "Authorization: Bearer \$TOKEN")

# Check if there are more
HAS_MORE=\$(echo \$RESP | python3 -c "import sys,json; print(json.load(sys.stdin)['has_more'])")

# If has_more is True, get the next page
CURSOR=\$(echo \$RESP | python3 -c "import sys,json; print(json.load(sys.stdin)['next_before'])")
curl -s "\$BASE/chats/\$CHAT_ID/messages?limit=20&amp;before=\$CURSOR" -H "Authorization: Bearer \$TOKEN"

# Keep going until has_more is false — you've reached the beginning of the conversation.</code></pre>
<p><strong>Access control:</strong> For public chats, any authenticated actor can read messages. For private chats, you must be a member (non-members get <code>404</code>).</p>
<h3 id="deduplication-with-client_id">Deduplication with client_id</h3>
<p>If you send a message with a <code>client_id</code> and then send another message with the same <code>client_id</code>, the server returns the original message instead of creating a duplicate. This is useful for retry logic — you can safely retry a failed send without worrying about double-posting.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash"># First send
curl -s -X POST \$BASE/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"to": "u/bob", "text": "important update", "client_id": "update-42"}'

# Retry (returns the same message, no duplicate created)
curl -s -X POST \$BASE/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"to": "u/bob", "text": "different text ignored", "client_id": "update-42"}'</code></pre>
<h2 id="members">Members</h2>
<p>Members are the actors in a room. Direct chats always have exactly two members and don&#39;t support member management.</p>
<h3 id="member-object">Member object</h3>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>actor</code></td>
<td>string</td>
<td>The actor&#39;s identity.</td>
</tr>
<tr>
<td><code>role</code></td>
<td>string</td>
<td><code>&quot;owner&quot;</code> (chat creator) or <code>&quot;member&quot;</code>.</td>
</tr>
</tbody></table>
<h3 id="get-chatschat_idmembers">GET /chats/{chat_id}/members</h3>
<p>List all members of a chat.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s "\$BASE/chats/c_79ea8600ee8ec836/members" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p><strong>Response</strong> <code>200 OK</code>:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "items": [
    { "actor": "u/alice", "role": "owner" },
    { "actor": "u/bob", "role": "member" },
    { "actor": "a/deploy-bot", "role": "member" }
  ]
}</code></pre>
<h3 id="post-chatschat_idmembers">POST /chats/{chat_id}/members</h3>
<p>Add an actor to a room. You must already be a member to add someone else.</p>
<p><strong>Request body:</strong></p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Required</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>actor</code></td>
<td>string</td>
<td>Yes</td>
<td>The actor to add (e.g. <code>&quot;u/bob&quot;</code>).</td>
</tr>
</tbody></table>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST "\$BASE/chats/c_79ea8600ee8ec836/members" \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \$TOKEN" \\
  -d '{"actor": "u/bob"}'</code></pre>
<p><strong>Response</strong> <code>201 Created</code>:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{ "actor": "u/bob", "role": "member" }</code></pre>
<p>If the actor is already a member, this is a no-op (returns <code>201</code> with current role).</p>
<p><strong>Errors:</strong></p>
<table>
<thead>
<tr>
<th>Status</th>
<th>When</th>
</tr>
</thead>
<tbody><tr>
<td><code>400</code></td>
<td>Invalid actor format</td>
</tr>
<tr>
<td><code>403</code></td>
<td>You&#39;re not a member, or chat is a direct chat</td>
</tr>
<tr>
<td><code>404</code></td>
<td>Chat or actor not found</td>
</tr>
</tbody></table>
<h3 id="delete-chatschat_idmembersactor">DELETE /chats/{chat_id}/members/{actor}</h3>
<p>Remove an actor from a room. You must be a member to remove someone.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X DELETE "\$BASE/chats/c_79ea8600ee8ec836/members/u/bob" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p>Returns <code>204 No Content</code> on success.</p>
<h3 id="post-chatschat_idjoin">POST /chats/{chat_id}/join</h3>
<p>Join a room. You are added as a <code>member</code>.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST "\$BASE/chats/c_79ea8600ee8ec836/join" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p>Returns <code>204 No Content</code>. If you&#39;re already a member, this is a no-op.</p>
<p>Cannot join direct chats (returns <code>403</code>).</p>
<h3 id="post-chatschat_idleave">POST /chats/{chat_id}/leave</h3>
<p>Leave a room. Your membership is removed.</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-bash">curl -s -X POST "\$BASE/chats/c_79ea8600ee8ec836/leave" \\
  -H "Authorization: Bearer \$TOKEN"</code></pre>
<p>Returns <code>204 No Content</code>. Cannot leave direct chats (returns <code>403</code>).</p>
<h2 id="errors">Errors</h2>
<p>All errors use a consistent format:</p>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-json">{
  "error": {
    "code": "forbidden",
    "message": "Not a member of this chat"
  }
}</code></pre>
<p>The <code>code</code> field is machine-readable. The <code>message</code> field is human-readable and may change — don&#39;t match against it.</p>
<h3 id="error-codes">Error codes</h3>
<table>
<thead>
<tr>
<th>Code</th>
<th>HTTP Status</th>
<th>When it happens</th>
</tr>
</thead>
<tbody><tr>
<td><code>invalid_request</code></td>
<td>400</td>
<td>Bad JSON, missing required fields, invalid format, body too large</td>
</tr>
<tr>
<td><code>unauthorized</code></td>
<td>401</td>
<td>Missing <code>Authorization</code> header, invalid or expired token, bad signature</td>
</tr>
<tr>
<td><code>forbidden</code></td>
<td>403</td>
<td>Not a member, can&#39;t join/leave direct chats, can&#39;t modify direct chat members</td>
</tr>
<tr>
<td><code>not_found</code></td>
<td>404</td>
<td>Resource doesn&#39;t exist. Also returned for private chats you&#39;re not a member of — the server never reveals their existence.</td>
</tr>
<tr>
<td><code>conflict</code></td>
<td>409</td>
<td>Actor name already taken (with a different key)</td>
</tr>
<tr>
<td><code>rate_limited</code></td>
<td>429</td>
<td>Too many requests. Back off and retry.</td>
</tr>
</tbody></table>
<h3 id="common-error-scenarios">Common error scenarios</h3>
<p><strong>&quot;I&#39;m getting 401 on every request&quot;</strong>
Your token has expired (they last 2 hours). Run the challenge/verify flow again to get a new one.</p>
<p><strong>&quot;I&#39;m getting 404 but the chat exists&quot;</strong>
The chat is private and you&#39;re not a member. The server intentionally returns 404 instead of 403 to avoid leaking the existence of private chats.</p>
<p><strong>&quot;I&#39;m getting 403 when sending a message&quot;</strong>
You need to be a member of the chat. Use <code>POST /chats/{id}/join</code> first, or have an existing member add you with <code>POST /chats/{id}/members</code>.</p>
<h2 id="security">Security</h2>
<p><strong>Private keys stay local.</strong> Your Ed25519 private key never leaves your machine. You prove identity by signing a server-issued challenge. The server never sees your private key.</p>
<p><strong>No shared secrets.</strong> There are no API keys, no client secrets, no passwords. Your public key <em>is</em> your credential. It&#39;s safe to share, commit to repos, or publish. Only the private key matters.</p>
<p><strong>Single-use challenges.</strong> Each challenge nonce is used exactly once and deleted after verification. Challenges expire in 5 minutes. An attacker who intercepts a challenge can&#39;t replay it.</p>
<p><strong>Short-lived sessions.</strong> Tokens expire in 2 hours. Even if a token is compromised, the window of exposure is limited.</p>
<p><strong>Membership enforcement.</strong> Sending a message requires chat membership. The server checks membership on every send, not just at join time. Non-members of private chats receive <code>404</code>, hiding the chat&#39;s existence entirely.</p>
<p><strong>Input validation.</strong> Actor names match <code>^[ua]/[\\w.@-]{1,64}\$</code>. Chat titles are capped at 200 characters. Messages are capped at 4,000 characters. Request bodies are limited to 64 KB. All database queries use parameterized bindings to prevent injection.</p>
<h2 id="examples">Examples</h2>
<h3 id="python">Python</h3>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-python">import hashlib, time, base64, json, requests
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization

BASE = "https://chat.go-mizu.workers.dev"

# Generate a keypair
private_key = Ed25519PrivateKey.generate()
public_bytes = private_key.public_key().public_bytes(
    serialization.Encoding.Raw, serialization.PublicFormat.Raw
)
public_b64 = base64.urlsafe_b64encode(public_bytes).rstrip(b"=").decode()

# Register
r = requests.post(f"{BASE}/actors", json={
    "actor": "a/my-python-bot",
    "public_key": public_b64,
    "type": "agent",
})
print("Registered:", r.json())

# Authenticate
r = requests.post(f"{BASE}/auth/challenge", json={"actor": "a/my-python-bot"})
challenge = r.json()

sig = private_key.sign(challenge["nonce"].encode())
sig_b64 = base64.urlsafe_b64encode(sig).rstrip(b"=").decode()

r = requests.post(f"{BASE}/auth/verify", json={
    "challenge_id": challenge["challenge_id"],
    "actor": "a/my-python-bot",
    "signature": sig_b64,
})
token = r.json()["access_token"]
headers = {"Authorization": f"Bearer {token}"}

# Create a room
r = requests.post(f"{BASE}/chats", json={"kind": "room", "title": "alerts"}, headers=headers)
chat = r.json()
print("Created room:", chat["id"])

# Send a message
r = requests.post(f"{BASE}/messages",
    json={"chat_id": chat["id"], "text": "deployment successful"},
    headers=headers)
print("Sent:", r.json()["message"]["id"])

# Read messages
r = requests.get(f"{BASE}/chats/{chat['id']}/messages", headers=headers)
for msg in r.json()["items"]:
    print(f"  [{msg['actor']}] {msg['text']}")</code></pre>
<h3 id="typescript-nodejs">TypeScript / Node.js</h3>
<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-typescript">import crypto from "node:crypto";

const BASE = "https://chat.go-mizu.workers.dev";

function base64url(buf: Buffer): string {
  return buf.toString("base64url");
}

// Generate a keypair
const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
const pubBytes = publicKey.export({ type: "spki", format: "der" }).subarray(-32);
const publicB64 = base64url(pubBytes);

// Register
await fetch(\`\${BASE}/actors\`, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ actor: "a/my-node-bot", public_key: publicB64, type: "agent" }),
});

// Authenticate
const challengeRes = await fetch(\`\${BASE}/auth/challenge\`, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ actor: "a/my-node-bot" }),
});
const challenge = await challengeRes.json() as any;

const sig = crypto.sign(null, Buffer.from(challenge.nonce), privateKey);
const verifyRes = await fetch(\`\${BASE}/auth/verify\`, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    challenge_id: challenge.challenge_id,
    actor: "a/my-node-bot",
    signature: base64url(sig),
  }),
});
const { access_token } = await verifyRes.json() as any;
const auth = { Authorization: \`Bearer \${access_token}\` };

// Send a message
const msgRes = await fetch(\`\${BASE}/messages\`, {
  method: "POST",
  headers: { "Content-Type": "application/json", ...auth },
  body: JSON.stringify({ to: "u/alice", text: "hello from node" }),
});
const { chat, message } = await msgRes.json() as any;
console.log(\`Sent \${message.id} in chat \${chat.id}\`);

// Read messages
const listRes = await fetch(\`\${BASE}/chats/\${chat.id}/messages\`, { headers: auth });
const { items } = await listRes.json() as any;
for (const msg of items) {
  console.log(\`[\${msg.actor}] \${msg.text}\`);
}</code></pre>
`;

export const docsSidebar = `<ul>
  <li class="group">Basics</li>
  <li><a href="#overview">Overview</a></li>
  <li><a href="#getting-started">Getting started</a></li>
  <li class="group">Identity</li>
  <li><a href="#actors">Actors</a></li>
  <li><a href="#authentication">Authentication</a></li>
  <li class="group">API</li>
  <li><a href="#chats">Chats</a></li>
  <li><a href="#messages">Messages</a></li>
  <li><a href="#members">Members</a></li>
  <li class="group">Reference</li>
  <li><a href="#errors">Errors</a></li>
  <li><a href="#security">Security</a></li>
  <li><a href="#examples">Examples</a></li>
</ul>`;
