// Wails generated bindings for DesktopApp
// These are auto-generated by wails when running `wails dev` or `wails build`
// This file provides type definitions for IDE support

export function GetDataDir(): Promise<string>;

export function GetBackendURL(): Promise<string>;

export function GetVersion(): Promise<{
  version: string;
  commit: string;
  buildTime: string;
}>;

export function ShowNotification(title: string, message: string): Promise<void>;

export function OpenExternal(url: string): void;

export function ShowOpenDialog(title: string, filters: string[]): Promise<string[]>;

export function ShowSaveDialog(title: string, defaultFilename: string): Promise<string>;

export function ShowDirectoryDialog(title: string): Promise<string>;

export function ReadFile(path: string): Promise<number[]>;

export function WriteFile(path: string, data: number[]): Promise<void>;

export function FileExists(path: string): Promise<boolean>;

export function GetHomeDir(): Promise<string>;

export function Minimize(): Promise<void>;

export function Maximize(): Promise<void>;

export function Close(): Promise<void>;

export function SetTitle(title: string): Promise<void>;

export function ToggleFullscreen(): Promise<void>;
