// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['DesktopApp']['Close']();
}

export function FileExists(arg1) {
  return window['go']['main']['DesktopApp']['FileExists'](arg1);
}

export function GetBackendURL() {
  return window['go']['main']['DesktopApp']['GetBackendURL']();
}

export function GetDataDir() {
  return window['go']['main']['DesktopApp']['GetDataDir']();
}

export function GetHomeDir() {
  return window['go']['main']['DesktopApp']['GetHomeDir']();
}

export function GetVersion() {
  return window['go']['main']['DesktopApp']['GetVersion']();
}

export function Maximize() {
  return window['go']['main']['DesktopApp']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['DesktopApp']['Minimize']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['DesktopApp']['OpenExternal'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['DesktopApp']['ReadFile'](arg1);
}

export function SetTitle(arg1) {
  return window['go']['main']['DesktopApp']['SetTitle'](arg1);
}

export function ShowDirectoryDialog(arg1) {
  return window['go']['main']['DesktopApp']['ShowDirectoryDialog'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ShowNotification'](arg1, arg2);
}

export function ShowOpenDialog(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ShowOpenDialog'](arg1, arg2);
}

export function ShowSaveDialog(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ShowSaveDialog'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['DesktopApp']['ToggleFullscreen']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['DesktopApp']['WriteFile'](arg1, arg2);
}
