// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetBackendURL():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetVersion():Promise<Record<string, string>>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function SetTitle(arg1:string):Promise<void>;

export function ShowDirectoryDialog(arg1:string):Promise<string>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowOpenDialog(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ShowSaveDialog(arg1:string,arg2:string):Promise<string>;

export function ToggleFullscreen():Promise<void>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
