package youtube

import "time"

type Video struct {
	VideoID            string    `json:"video_id"`
	Title              string    `json:"title"`
	Description        string    `json:"description"`
	ChannelID          string    `json:"channel_id"`
	ChannelName        string    `json:"channel_name"`
	DurationSeconds    int       `json:"duration_seconds"`
	DurationText       string    `json:"duration_text"`
	ViewCount          int64     `json:"view_count"`
	CommentCount       int64     `json:"comment_count"`
	LikeCount          int64     `json:"like_count"`
	PublishedText      string    `json:"published_text"`
	PublishedAt        time.Time `json:"published_at"`
	UploadDate         string    `json:"upload_date"`
	IsLive             bool      `json:"is_live"`
	IsShort            bool      `json:"is_short"`
	Category           string    `json:"category"`
	Tags               []string  `json:"tags"`
	ThumbnailURL       string    `json:"thumbnail_url"`
	URL                string    `json:"url"`
	EmbedURL           string    `json:"embed_url"`
	Transcript         string    `json:"transcript"`
	TranscriptLanguage string    `json:"transcript_language"`
	FetchedAt          time.Time `json:"fetched_at"`
}

type Channel struct {
	ChannelID         string    `json:"channel_id"`
	Handle            string    `json:"handle"`
	Title             string    `json:"title"`
	Description       string    `json:"description"`
	AvatarURL         string    `json:"avatar_url"`
	BannerURL         string    `json:"banner_url"`
	SubscribersText   string    `json:"subscribers_text"`
	VideosText        string    `json:"videos_text"`
	ViewsText         string    `json:"views_text"`
	Country           string    `json:"country"`
	JoinedDateText    string    `json:"joined_date_text"`
	UploadsPlaylistID string    `json:"uploads_playlist_id"`
	URL               string    `json:"url"`
	FetchedAt         time.Time `json:"fetched_at"`
}

type Playlist struct {
	PlaylistID      string    `json:"playlist_id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	ChannelID       string    `json:"channel_id"`
	ChannelName     string    `json:"channel_name"`
	VideoCount      int       `json:"video_count"`
	ViewCountText   string    `json:"view_count_text"`
	LastUpdatedText string    `json:"last_updated_text"`
	URL             string    `json:"url"`
	FetchedAt       time.Time `json:"fetched_at"`
}

type PlaylistVideo struct {
	PlaylistID string `json:"playlist_id"`
	VideoID    string `json:"video_id"`
	Position   int    `json:"position"`
}

type RelatedVideo struct {
	VideoID        string `json:"video_id"`
	RelatedVideoID string `json:"related_video_id"`
	Position       int    `json:"position"`
}

type CaptionTrack struct {
	VideoID         string    `json:"video_id"`
	LanguageCode    string    `json:"language_code"`
	Name            string    `json:"name"`
	BaseURL         string    `json:"base_url"`
	Kind            string    `json:"kind"`
	IsAutoGenerated bool      `json:"is_auto_generated"`
	FetchedAt       time.Time `json:"fetched_at"`
}

type SearchResult struct {
	EntityType string `json:"entity_type"`
	ID         string `json:"id"`
	Title      string `json:"title"`
	URL        string `json:"url"`
}

type QueueItem struct {
	ID         int64
	URL        string
	EntityType string
	Priority   int
}

type JobRecord struct {
	JobID       string
	Name        string
	Type        string
	Status      string
	StartedAt   time.Time
	CompletedAt time.Time
}

type PageData struct {
	HTML          string
	InitialData   any
	PlayerResp    any
	YTCFG         map[string]any
	APIKey        string
	ClientVersion string
	VisitorData   string
}
