#!/usr/bin/env node
/**
 * Converts docs.md → src/docs-content.ts
 *
 * Parses markdown with `marked`, extracts h2 headings for the sidebar TOC,
 * and writes a TypeScript module exporting both.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const md = readFileSync(resolve(root, "docs.md"), "utf-8");

// Custom renderer to add id attributes to headings and copy buttons to code blocks
const renderer = new marked.Renderer();

renderer.heading = function ({ text, depth }) {
  const slug = text
    .toLowerCase()
    .replace(/<[^>]*>/g, "")
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
  return `<h${depth} id="${slug}">${text}</h${depth}>\n`;
};

renderer.code = function ({ text, lang }) {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `<pre><button class="cb" onclick="cp(this)">Copy</button><code class="lang-${lang || ""}">${escaped}</code></pre>\n`;
};

const html = marked(md, { renderer });

// Extract h2 headings for sidebar TOC
const toc = [];
const h2re = /<h2 id="([^"]+)">([^<]+)<\/h2>/g;
let match;
while ((match = h2re.exec(html)) !== null) {
  toc.push({ id: match[1], title: match[2] });
}

// Group TOC into sections
const groups = [
  { label: "Basics", ids: ["overview", "getting-started"] },
  { label: "Identity", ids: ["actors", "authentication"] },
  { label: "API", ids: ["chats", "messages", "members"] },
  { label: "Reference", ids: ["errors", "security", "examples"] },
];

function buildSidebarHtml() {
  let out = "<ul>\n";
  for (const g of groups) {
    out += `  <li class="group">${g.label}</li>\n`;
    for (const id of g.ids) {
      const entry = toc.find((t) => t.id === id);
      if (entry) {
        out += `  <li><a href="#${entry.id}">${entry.title}</a></li>\n`;
      }
    }
  }
  out += "</ul>";
  return out;
}

const sidebarHtml = buildSidebarHtml();

// Escape backticks and backslashes for template literal
function esc(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

const output = `// AUTO-GENERATED by scripts/build-docs.mjs — do not edit
// Source: docs.md

export const docsContent = \`${esc(html)}\`;

export const docsSidebar = \`${esc(sidebarHtml)}\`;
`;

writeFileSync(resolve(root, "src", "docs-content.ts"), output);
console.log("Built src/docs-content.ts from docs.md");
