/**
 * Build script: reads SVG fragments from src/avatars/ and generates src/avatar-data.gen.ts
 * Run: node scripts/build-avatars.mjs
 */

import { readFileSync, readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const AVATARS_DIR = join(__dirname, "..", "src", "avatars");
const OUT_FILE = join(__dirname, "..", "src", "avatar-data.gen.ts");

// Categories and their sort order within the array
const CATEGORIES = [
  { dir: "face", name: "FACES", sort: naturalSort },
  { dir: "eyes", name: "EYES", sort: (a, b) => {
    const order = ["Normal", "Closed", "Angry", "Cynic", "Sad", "Thin"];
    return order.indexOf(a) - order.indexOf(b);
  }},
  { dir: "mouth", name: "MOUTHS", sort: (a, b) => {
    const order = [
      "NormalSmile1", "NormalSmile2", "OpenMouth", "Sad", "Nervous",
      "OpenTooth", "Angry", "Eat", "Hate", "Mouth11", "Whistle",
    ];
    return order.indexOf(a) - order.indexOf(b);
  }},
  { dir: "hair", name: "HAIRS", sort: naturalSort },
  { dir: "accessories", name: "ACCESSORIES", sort: (a, b) => {
    const order = [
      "Glasses", "RoundedGlasses", "Blush",
      "Beard1", "Beard2", "Beard3", "Beard4",
      "Moustache1", "Moustache2", "Moustache3", "Moustache4",
      "StylishGlasses", "Cap", "Earphone",
      "FuturisticGlasses", "Mask", "MaskGoogle", "WaitressTie",
    ];
    return order.indexOf(a) - order.indexOf(b);
  }},
];

function naturalSort(a, b) {
  return a.localeCompare(b, undefined, { numeric: true });
}

function escapeBacktick(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

let output = `// AUTO-GENERATED by scripts/build-avatars.mjs — do not edit\n`;
output += `// Source SVGs in src/avatars/\n\n`;

for (const { dir, name, sort } of CATEGORIES) {
  const catDir = join(AVATARS_DIR, dir);
  const files = readdirSync(catDir)
    .filter((f) => f.endsWith(".svg"))
    .map((f) => f.replace(".svg", ""))
    .sort(sort);

  output += `export const ${name}: string[] = [\n`;
  for (const file of files) {
    const svg = readFileSync(join(catDir, `${file}.svg`), "utf-8").trim();
    // Collapse to single line for compactness
    const oneLine = svg.replace(/\n\s*/g, "");
    output += `  // ${file}\n`;
    output += `  \`${escapeBacktick(oneLine)}\`,\n\n`;
  }
  output += `];\n\n`;
}

writeFileSync(OUT_FILE, output);
const stats = CATEGORIES.map((c) => {
  const n = readdirSync(join(AVATARS_DIR, c.dir)).filter((f) => f.endsWith(".svg")).length;
  return `${c.dir}: ${n}`;
}).join(", ");
console.log(`Generated ${OUT_FILE}`);
console.log(`Parts: ${stats}`);
