// File: lib/storage/transport/grpc/proto/storage.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: storage.proto

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_CreateBucket_FullMethodName      = "/storage.v1.StorageService/CreateBucket"
	StorageService_DeleteBucket_FullMethodName      = "/storage.v1.StorageService/DeleteBucket"
	StorageService_GetBucket_FullMethodName         = "/storage.v1.StorageService/GetBucket"
	StorageService_ListBuckets_FullMethodName       = "/storage.v1.StorageService/ListBuckets"
	StorageService_StatObject_FullMethodName        = "/storage.v1.StorageService/StatObject"
	StorageService_DeleteObject_FullMethodName      = "/storage.v1.StorageService/DeleteObject"
	StorageService_CopyObject_FullMethodName        = "/storage.v1.StorageService/CopyObject"
	StorageService_MoveObject_FullMethodName        = "/storage.v1.StorageService/MoveObject"
	StorageService_ListObjects_FullMethodName       = "/storage.v1.StorageService/ListObjects"
	StorageService_ReadObject_FullMethodName        = "/storage.v1.StorageService/ReadObject"
	StorageService_WriteObject_FullMethodName       = "/storage.v1.StorageService/WriteObject"
	StorageService_InitMultipart_FullMethodName     = "/storage.v1.StorageService/InitMultipart"
	StorageService_UploadPart_FullMethodName        = "/storage.v1.StorageService/UploadPart"
	StorageService_ListParts_FullMethodName         = "/storage.v1.StorageService/ListParts"
	StorageService_CompleteMultipart_FullMethodName = "/storage.v1.StorageService/CompleteMultipart"
	StorageService_AbortMultipart_FullMethodName    = "/storage.v1.StorageService/AbortMultipart"
	StorageService_SignedURL_FullMethodName         = "/storage.v1.StorageService/SignedURL"
	StorageService_GetFeatures_FullMethodName       = "/storage.v1.StorageService/GetFeatures"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService exposes storage.Storage operations over gRPC.
type StorageServiceClient interface {
	// Bucket Operations
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*BucketInfo, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBucket(ctx context.Context, in *GetBucketRequest, opts ...grpc.CallOption) (*BucketInfo, error)
	ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BucketInfo], error)
	// Object Operations
	StatObject(ctx context.Context, in *StatObjectRequest, opts ...grpc.CallOption) (*ObjectInfo, error)
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CopyObject(ctx context.Context, in *CopyObjectRequest, opts ...grpc.CallOption) (*ObjectInfo, error)
	MoveObject(ctx context.Context, in *MoveObjectRequest, opts ...grpc.CallOption) (*ObjectInfo, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectInfo], error)
	// Streaming Data Operations
	ReadObject(ctx context.Context, in *ReadObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadObjectResponse], error)
	WriteObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteObjectRequest, ObjectInfo], error)
	// Multipart Upload Operations
	InitMultipart(ctx context.Context, in *InitMultipartRequest, opts ...grpc.CallOption) (*MultipartUpload, error)
	UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartRequest, PartInfo], error)
	ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PartInfo], error)
	CompleteMultipart(ctx context.Context, in *CompleteMultipartRequest, opts ...grpc.CallOption) (*ObjectInfo, error)
	AbortMultipart(ctx context.Context, in *AbortMultipartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Signed URL
	SignedURL(ctx context.Context, in *SignedURLRequest, opts ...grpc.CallOption) (*SignedURLResponse, error)
	// Features
	GetFeatures(ctx context.Context, in *GetFeaturesRequest, opts ...grpc.CallOption) (*Features, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*BucketInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketInfo)
	err := c.cc.Invoke(ctx, StorageService_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageService_DeleteBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetBucket(ctx context.Context, in *GetBucketRequest, opts ...grpc.CallOption) (*BucketInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketInfo)
	err := c.cc.Invoke(ctx, StorageService_GetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BucketInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_ListBuckets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListBucketsRequest, BucketInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListBucketsClient = grpc.ServerStreamingClient[BucketInfo]

func (c *storageServiceClient) StatObject(ctx context.Context, in *StatObjectRequest, opts ...grpc.CallOption) (*ObjectInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectInfo)
	err := c.cc.Invoke(ctx, StorageService_StatObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CopyObject(ctx context.Context, in *CopyObjectRequest, opts ...grpc.CallOption) (*ObjectInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectInfo)
	err := c.cc.Invoke(ctx, StorageService_CopyObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) MoveObject(ctx context.Context, in *MoveObjectRequest, opts ...grpc.CallOption) (*ObjectInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectInfo)
	err := c.cc.Invoke(ctx, StorageService_MoveObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_ListObjects_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListObjectsRequest, ObjectInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListObjectsClient = grpc.ServerStreamingClient[ObjectInfo]

func (c *storageServiceClient) ReadObject(ctx context.Context, in *ReadObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[2], StorageService_ReadObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadObjectRequest, ReadObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadObjectClient = grpc.ServerStreamingClient[ReadObjectResponse]

func (c *storageServiceClient) WriteObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteObjectRequest, ObjectInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[3], StorageService_WriteObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteObjectRequest, ObjectInfo]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_WriteObjectClient = grpc.ClientStreamingClient[WriteObjectRequest, ObjectInfo]

func (c *storageServiceClient) InitMultipart(ctx context.Context, in *InitMultipartRequest, opts ...grpc.CallOption) (*MultipartUpload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultipartUpload)
	err := c.cc.Invoke(ctx, StorageService_InitMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartRequest, PartInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[4], StorageService_UploadPart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPartRequest, PartInfo]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_UploadPartClient = grpc.ClientStreamingClient[UploadPartRequest, PartInfo]

func (c *storageServiceClient) ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PartInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[5], StorageService_ListParts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListPartsRequest, PartInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListPartsClient = grpc.ServerStreamingClient[PartInfo]

func (c *storageServiceClient) CompleteMultipart(ctx context.Context, in *CompleteMultipartRequest, opts ...grpc.CallOption) (*ObjectInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectInfo)
	err := c.cc.Invoke(ctx, StorageService_CompleteMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) AbortMultipart(ctx context.Context, in *AbortMultipartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageService_AbortMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SignedURL(ctx context.Context, in *SignedURLRequest, opts ...grpc.CallOption) (*SignedURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedURLResponse)
	err := c.cc.Invoke(ctx, StorageService_SignedURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFeatures(ctx context.Context, in *GetFeaturesRequest, opts ...grpc.CallOption) (*Features, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Features)
	err := c.cc.Invoke(ctx, StorageService_GetFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService exposes storage.Storage operations over gRPC.
type StorageServiceServer interface {
	// Bucket Operations
	CreateBucket(context.Context, *CreateBucketRequest) (*BucketInfo, error)
	DeleteBucket(context.Context, *DeleteBucketRequest) (*emptypb.Empty, error)
	GetBucket(context.Context, *GetBucketRequest) (*BucketInfo, error)
	ListBuckets(*ListBucketsRequest, grpc.ServerStreamingServer[BucketInfo]) error
	// Object Operations
	StatObject(context.Context, *StatObjectRequest) (*ObjectInfo, error)
	DeleteObject(context.Context, *DeleteObjectRequest) (*emptypb.Empty, error)
	CopyObject(context.Context, *CopyObjectRequest) (*ObjectInfo, error)
	MoveObject(context.Context, *MoveObjectRequest) (*ObjectInfo, error)
	ListObjects(*ListObjectsRequest, grpc.ServerStreamingServer[ObjectInfo]) error
	// Streaming Data Operations
	ReadObject(*ReadObjectRequest, grpc.ServerStreamingServer[ReadObjectResponse]) error
	WriteObject(grpc.ClientStreamingServer[WriteObjectRequest, ObjectInfo]) error
	// Multipart Upload Operations
	InitMultipart(context.Context, *InitMultipartRequest) (*MultipartUpload, error)
	UploadPart(grpc.ClientStreamingServer[UploadPartRequest, PartInfo]) error
	ListParts(*ListPartsRequest, grpc.ServerStreamingServer[PartInfo]) error
	CompleteMultipart(context.Context, *CompleteMultipartRequest) (*ObjectInfo, error)
	AbortMultipart(context.Context, *AbortMultipartRequest) (*emptypb.Empty, error)
	// Signed URL
	SignedURL(context.Context, *SignedURLRequest) (*SignedURLResponse, error)
	// Features
	GetFeatures(context.Context, *GetFeaturesRequest) (*Features, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) CreateBucket(context.Context, *CreateBucketRequest) (*BucketInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedStorageServiceServer) DeleteBucket(context.Context, *DeleteBucketRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (UnimplementedStorageServiceServer) GetBucket(context.Context, *GetBucketRequest) (*BucketInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucket not implemented")
}
func (UnimplementedStorageServiceServer) ListBuckets(*ListBucketsRequest, grpc.ServerStreamingServer[BucketInfo]) error {
	return status.Error(codes.Unimplemented, "method ListBuckets not implemented")
}
func (UnimplementedStorageServiceServer) StatObject(context.Context, *StatObjectRequest) (*ObjectInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StatObject not implemented")
}
func (UnimplementedStorageServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedStorageServiceServer) CopyObject(context.Context, *CopyObjectRequest) (*ObjectInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyObject not implemented")
}
func (UnimplementedStorageServiceServer) MoveObject(context.Context, *MoveObjectRequest) (*ObjectInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveObject not implemented")
}
func (UnimplementedStorageServiceServer) ListObjects(*ListObjectsRequest, grpc.ServerStreamingServer[ObjectInfo]) error {
	return status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedStorageServiceServer) ReadObject(*ReadObjectRequest, grpc.ServerStreamingServer[ReadObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadObject not implemented")
}
func (UnimplementedStorageServiceServer) WriteObject(grpc.ClientStreamingServer[WriteObjectRequest, ObjectInfo]) error {
	return status.Error(codes.Unimplemented, "method WriteObject not implemented")
}
func (UnimplementedStorageServiceServer) InitMultipart(context.Context, *InitMultipartRequest) (*MultipartUpload, error) {
	return nil, status.Error(codes.Unimplemented, "method InitMultipart not implemented")
}
func (UnimplementedStorageServiceServer) UploadPart(grpc.ClientStreamingServer[UploadPartRequest, PartInfo]) error {
	return status.Error(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedStorageServiceServer) ListParts(*ListPartsRequest, grpc.ServerStreamingServer[PartInfo]) error {
	return status.Error(codes.Unimplemented, "method ListParts not implemented")
}
func (UnimplementedStorageServiceServer) CompleteMultipart(context.Context, *CompleteMultipartRequest) (*ObjectInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteMultipart not implemented")
}
func (UnimplementedStorageServiceServer) AbortMultipart(context.Context, *AbortMultipartRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortMultipart not implemented")
}
func (UnimplementedStorageServiceServer) SignedURL(context.Context, *SignedURLRequest) (*SignedURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignedURL not implemented")
}
func (UnimplementedStorageServiceServer) GetFeatures(context.Context, *GetFeaturesRequest) (*Features, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatures not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetBucket(ctx, req.(*GetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListBuckets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBucketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ListBuckets(m, &grpc.GenericServerStream[ListBucketsRequest, BucketInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListBucketsServer = grpc.ServerStreamingServer[BucketInfo]

func _StorageService_StatObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).StatObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_StatObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).StatObject(ctx, req.(*StatObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CopyObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CopyObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CopyObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CopyObject(ctx, req.(*CopyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_MoveObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).MoveObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_MoveObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).MoveObject(ctx, req.(*MoveObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListObjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListObjectsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ListObjects(m, &grpc.GenericServerStream[ListObjectsRequest, ObjectInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListObjectsServer = grpc.ServerStreamingServer[ObjectInfo]

func _StorageService_ReadObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ReadObject(m, &grpc.GenericServerStream[ReadObjectRequest, ReadObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadObjectServer = grpc.ServerStreamingServer[ReadObjectResponse]

func _StorageService_WriteObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).WriteObject(&grpc.GenericServerStream[WriteObjectRequest, ObjectInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_WriteObjectServer = grpc.ClientStreamingServer[WriteObjectRequest, ObjectInfo]

func _StorageService_InitMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).InitMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_InitMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).InitMultipart(ctx, req.(*InitMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UploadPart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).UploadPart(&grpc.GenericServerStream[UploadPartRequest, PartInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_UploadPartServer = grpc.ClientStreamingServer[UploadPartRequest, PartInfo]

func _StorageService_ListParts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPartsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ListParts(m, &grpc.GenericServerStream[ListPartsRequest, PartInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListPartsServer = grpc.ServerStreamingServer[PartInfo]

func _StorageService_CompleteMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CompleteMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CompleteMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CompleteMultipart(ctx, req.(*CompleteMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_AbortMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).AbortMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_AbortMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).AbortMultipart(ctx, req.(*AbortMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SignedURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SignedURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SignedURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SignedURL(ctx, req.(*SignedURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetFeatures(ctx, req.(*GetFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _StorageService_CreateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _StorageService_DeleteBucket_Handler,
		},
		{
			MethodName: "GetBucket",
			Handler:    _StorageService_GetBucket_Handler,
		},
		{
			MethodName: "StatObject",
			Handler:    _StorageService_StatObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _StorageService_DeleteObject_Handler,
		},
		{
			MethodName: "CopyObject",
			Handler:    _StorageService_CopyObject_Handler,
		},
		{
			MethodName: "MoveObject",
			Handler:    _StorageService_MoveObject_Handler,
		},
		{
			MethodName: "InitMultipart",
			Handler:    _StorageService_InitMultipart_Handler,
		},
		{
			MethodName: "CompleteMultipart",
			Handler:    _StorageService_CompleteMultipart_Handler,
		},
		{
			MethodName: "AbortMultipart",
			Handler:    _StorageService_AbortMultipart_Handler,
		},
		{
			MethodName: "SignedURL",
			Handler:    _StorageService_SignedURL_Handler,
		},
		{
			MethodName: "GetFeatures",
			Handler:    _StorageService_GetFeatures_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBuckets",
			Handler:       _StorageService_ListBuckets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListObjects",
			Handler:       _StorageService_ListObjects_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadObject",
			Handler:       _StorageService_ReadObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteObject",
			Handler:       _StorageService_WriteObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadPart",
			Handler:       _StorageService_UploadPart_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ListParts",
			Handler:       _StorageService_ListParts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage.proto",
}
