// File: lib/storage/transport/grpc/proto/storage.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BucketInfo describes a bucket.
type BucketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Public        bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketInfo) Reset() {
	*x = BucketInfo{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketInfo) ProtoMessage() {}

func (x *BucketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketInfo.ProtoReflect.Descriptor instead.
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *BucketInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BucketInfo) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *BucketInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ObjectInfo describes stored data or a logical directory entry.
type ObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Etag          string                 `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Updated       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	Hash          map[string]string      `protobuf:"bytes,9,rep,name=hash,proto3" json:"hash,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDir         bool                   `protobuf:"varint,11,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectInfo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ObjectInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ObjectInfo) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ObjectInfo) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *ObjectInfo) GetHash() map[string]string {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ObjectInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ObjectInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

// MultipartUpload describes an in-progress multipart upload.
type MultipartUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipartUpload) Reset() {
	*x = MultipartUpload{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipartUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUpload) ProtoMessage() {}

func (x *MultipartUpload) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUpload.ProtoReflect.Descriptor instead.
func (*MultipartUpload) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *MultipartUpload) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MultipartUpload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MultipartUpload) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *MultipartUpload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PartInfo describes a single uploaded part.
type PartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Hash          map[string]string      `protobuf:"bytes,4,rep,name=hash,proto3" json:"hash,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartInfo) Reset() {
	*x = PartInfo{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInfo) ProtoMessage() {}

func (x *PartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInfo.ProtoReflect.Descriptor instead.
func (*PartInfo) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *PartInfo) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PartInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PartInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *PartInfo) GetHash() map[string]string {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *PartInfo) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

// Features describes supported capabilities.
type Features struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      map[string]bool        `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Features) Reset() {
	*x = Features{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Features) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

type CreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBucketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBucketRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBucketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteBucketRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketRequest) Reset() {
	*x = GetBucketRequest{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketRequest) ProtoMessage() {}

func (x *GetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketRequest.ProtoReflect.Descriptor instead.
func (*GetBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *GetBucketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ListBucketsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBucketsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBucketsRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type StatObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatObjectRequest) Reset() {
	*x = StatObjectRequest{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatObjectRequest) ProtoMessage() {}

func (x *StatObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatObjectRequest.ProtoReflect.Descriptor instead.
func (*StatObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *StatObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StatObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatObjectRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeleteObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DeleteObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteObjectRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type CopyObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcBucket     string                 `protobuf:"bytes,1,opt,name=src_bucket,json=srcBucket,proto3" json:"src_bucket,omitempty"`
	SrcKey        string                 `protobuf:"bytes,2,opt,name=src_key,json=srcKey,proto3" json:"src_key,omitempty"`
	DstBucket     string                 `protobuf:"bytes,3,opt,name=dst_bucket,json=dstBucket,proto3" json:"dst_bucket,omitempty"`
	DstKey        string                 `protobuf:"bytes,4,opt,name=dst_key,json=dstKey,proto3" json:"dst_key,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyObjectRequest) Reset() {
	*x = CopyObjectRequest{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectRequest) ProtoMessage() {}

func (x *CopyObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectRequest.ProtoReflect.Descriptor instead.
func (*CopyObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

func (x *CopyObjectRequest) GetSrcBucket() string {
	if x != nil {
		return x.SrcBucket
	}
	return ""
}

func (x *CopyObjectRequest) GetSrcKey() string {
	if x != nil {
		return x.SrcKey
	}
	return ""
}

func (x *CopyObjectRequest) GetDstBucket() string {
	if x != nil {
		return x.DstBucket
	}
	return ""
}

func (x *CopyObjectRequest) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

func (x *CopyObjectRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type MoveObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcBucket     string                 `protobuf:"bytes,1,opt,name=src_bucket,json=srcBucket,proto3" json:"src_bucket,omitempty"`
	SrcKey        string                 `protobuf:"bytes,2,opt,name=src_key,json=srcKey,proto3" json:"src_key,omitempty"`
	DstBucket     string                 `protobuf:"bytes,3,opt,name=dst_bucket,json=dstBucket,proto3" json:"dst_bucket,omitempty"`
	DstKey        string                 `protobuf:"bytes,4,opt,name=dst_key,json=dstKey,proto3" json:"dst_key,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveObjectRequest) Reset() {
	*x = MoveObjectRequest{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectRequest) ProtoMessage() {}

func (x *MoveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectRequest.ProtoReflect.Descriptor instead.
func (*MoveObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *MoveObjectRequest) GetSrcBucket() string {
	if x != nil {
		return x.SrcBucket
	}
	return ""
}

func (x *MoveObjectRequest) GetSrcKey() string {
	if x != nil {
		return x.SrcKey
	}
	return ""
}

func (x *MoveObjectRequest) GetDstBucket() string {
	if x != nil {
		return x.DstBucket
	}
	return ""
}

func (x *MoveObjectRequest) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

func (x *MoveObjectRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *ListObjectsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListObjectsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListObjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListObjectsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListObjectsRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ReadObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"` // 0 or negative means full object
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadObjectRequest) Reset() {
	*x = ReadObjectRequest{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadObjectRequest) ProtoMessage() {}

func (x *ReadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadObjectRequest.ProtoReflect.Descriptor instead.
func (*ReadObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *ReadObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ReadObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadObjectRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadObjectRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ReadObjectRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ReadObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ReadObjectResponse_Metadata
	//	*ReadObjectResponse_Data
	Payload       isReadObjectResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadObjectResponse) Reset() {
	*x = ReadObjectResponse{}
	mi := &file_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadObjectResponse) ProtoMessage() {}

func (x *ReadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadObjectResponse.ProtoReflect.Descriptor instead.
func (*ReadObjectResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

func (x *ReadObjectResponse) GetPayload() isReadObjectResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReadObjectResponse) GetMetadata() *ObjectInfo {
	if x != nil {
		if x, ok := x.Payload.(*ReadObjectResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ReadObjectResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ReadObjectResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isReadObjectResponse_Payload interface {
	isReadObjectResponse_Payload()
}

type ReadObjectResponse_Metadata struct {
	Metadata *ObjectInfo `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message contains metadata
}

type ReadObjectResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Subsequent messages contain data chunks
}

func (*ReadObjectResponse_Metadata) isReadObjectResponse_Payload() {}

func (*ReadObjectResponse_Data) isReadObjectResponse_Payload() {}

type WriteObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteObjectRequest_Metadata
	//	*WriteObjectRequest_Data
	Payload       isWriteObjectRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteObjectRequest) Reset() {
	*x = WriteObjectRequest{}
	mi := &file_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteObjectRequest) ProtoMessage() {}

func (x *WriteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteObjectRequest.ProtoReflect.Descriptor instead.
func (*WriteObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16}
}

func (x *WriteObjectRequest) GetPayload() isWriteObjectRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteObjectRequest) GetMetadata() *WriteObjectMetadata {
	if x != nil {
		if x, ok := x.Payload.(*WriteObjectRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *WriteObjectRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteObjectRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isWriteObjectRequest_Payload interface {
	isWriteObjectRequest_Payload()
}

type WriteObjectRequest_Metadata struct {
	Metadata *WriteObjectMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message must be metadata
}

type WriteObjectRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Subsequent messages are data chunks
}

func (*WriteObjectRequest_Metadata) isWriteObjectRequest_Payload() {}

func (*WriteObjectRequest_Data) isWriteObjectRequest_Payload() {}

type WriteObjectMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // -1 for unknown/streaming
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteObjectMetadata) Reset() {
	*x = WriteObjectMetadata{}
	mi := &file_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteObjectMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteObjectMetadata) ProtoMessage() {}

func (x *WriteObjectMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteObjectMetadata.ProtoReflect.Descriptor instead.
func (*WriteObjectMetadata) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{17}
}

func (x *WriteObjectMetadata) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *WriteObjectMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteObjectMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WriteObjectMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *WriteObjectMetadata) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type InitMultipartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMultipartRequest) Reset() {
	*x = InitMultipartRequest{}
	mi := &file_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMultipartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMultipartRequest) ProtoMessage() {}

func (x *InitMultipartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMultipartRequest.ProtoReflect.Descriptor instead.
func (*InitMultipartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{18}
}

func (x *InitMultipartRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *InitMultipartRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InitMultipartRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitMultipartRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type UploadPartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadPartRequest_Metadata
	//	*UploadPartRequest_Data
	Payload       isUploadPartRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartRequest) Reset() {
	*x = UploadPartRequest{}
	mi := &file_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRequest) ProtoMessage() {}

func (x *UploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRequest.ProtoReflect.Descriptor instead.
func (*UploadPartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{19}
}

func (x *UploadPartRequest) GetPayload() isUploadPartRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadPartRequest) GetMetadata() *UploadPartMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadPartRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadPartRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadPartRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadPartRequest_Payload interface {
	isUploadPartRequest_Payload()
}

type UploadPartRequest_Metadata struct {
	Metadata *UploadPartMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadPartRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadPartRequest_Metadata) isUploadPartRequest_Payload() {}

func (*UploadPartRequest_Data) isUploadPartRequest_Payload() {}

type UploadPartMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PartNumber    int32                  `protobuf:"varint,4,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartMetadata) Reset() {
	*x = UploadPartMetadata{}
	mi := &file_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartMetadata) ProtoMessage() {}

func (x *UploadPartMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartMetadata.ProtoReflect.Descriptor instead.
func (*UploadPartMetadata) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{20}
}

func (x *UploadPartMetadata) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadPartMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadPartMetadata) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartMetadata) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPartMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadPartMetadata) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListPartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{21}
}

func (x *ListPartsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListPartsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListPartsRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ListPartsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPartsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPartsRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type CompleteMultipartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Parts         []*PartInfo            `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartRequest) Reset() {
	*x = CompleteMultipartRequest{}
	mi := &file_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartRequest) ProtoMessage() {}

func (x *CompleteMultipartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartRequest.ProtoReflect.Descriptor instead.
func (*CompleteMultipartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{22}
}

func (x *CompleteMultipartRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CompleteMultipartRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CompleteMultipartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteMultipartRequest) GetParts() []*PartInfo {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CompleteMultipartRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type AbortMultipartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartRequest) Reset() {
	*x = AbortMultipartRequest{}
	mi := &file_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartRequest) ProtoMessage() {}

func (x *AbortMultipartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartRequest.ProtoReflect.Descriptor instead.
func (*AbortMultipartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{23}
}

func (x *AbortMultipartRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AbortMultipartRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AbortMultipartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *AbortMultipartRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type SignedURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Expires       *durationpb.Duration   `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	Options       map[string][]byte      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedURLRequest) Reset() {
	*x = SignedURLRequest{}
	mi := &file_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedURLRequest) ProtoMessage() {}

func (x *SignedURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedURLRequest.ProtoReflect.Descriptor instead.
func (*SignedURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{24}
}

func (x *SignedURLRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SignedURLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SignedURLRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SignedURLRequest) GetExpires() *durationpb.Duration {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *SignedURLRequest) GetOptions() map[string][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type SignedURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedURLResponse) Reset() {
	*x = SignedURLResponse{}
	mi := &file_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedURLResponse) ProtoMessage() {}

func (x *SignedURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedURLResponse.ProtoReflect.Descriptor instead.
func (*SignedURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{25}
}

func (x *SignedURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"` // Empty for storage-level features
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesRequest) Reset() {
	*x = GetFeaturesRequest{}
	mi := &file_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesRequest) ProtoMessage() {}

func (x *GetFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{26}
}

func (x *GetFeaturesRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\n" +
	"storage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\n" +
	"BucketInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.storage.v1.BucketInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x04\n" +
	"\n" +
	"ObjectInfo\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x124\n" +
	"\acreated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\aupdated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x124\n" +
	"\x04hash\x18\t \x03(\v2 .storage.v1.ObjectInfo.HashEntryR\x04hash\x12@\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2$.storage.v1.ObjectInfo.MetadataEntryR\bmetadata\x12\x15\n" +
	"\x06is_dir\x18\v \x01(\bR\x05isDir\x1a7\n" +
	"\tHashEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x0fMultipartUpload\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).storage.v1.MultipartUpload.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\bPartInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x122\n" +
	"\x04hash\x18\x04 \x03(\v2\x1e.storage.v1.PartInfo.HashEntryR\x04hash\x12?\n" +
	"\rlast_modified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x1a7\n" +
	"\tHashEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\bFeatures\x12>\n" +
	"\bfeatures\x18\x01 \x03(\v2\".storage.v1.Features.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xad\x01\n" +
	"\x13CreateBucketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\aoptions\x18\x02 \x03(\v2,.storage.v1.CreateBucketRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xad\x01\n" +
	"\x13DeleteBucketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\aoptions\x18\x02 \x03(\v2,.storage.v1.DeleteBucketRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"&\n" +
	"\x10GetBucketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc5\x01\n" +
	"\x12ListBucketsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12E\n" +
	"\aoptions\x18\x03 \x03(\v2+.storage.v1.ListBucketsRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xbf\x01\n" +
	"\x11StatObjectRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12D\n" +
	"\aoptions\x18\x03 \x03(\v2*.storage.v1.StatObjectRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x13DeleteObjectRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12F\n" +
	"\aoptions\x18\x03 \x03(\v2,.storage.v1.DeleteObjectRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x85\x02\n" +
	"\x11CopyObjectRequest\x12\x1d\n" +
	"\n" +
	"src_bucket\x18\x01 \x01(\tR\tsrcBucket\x12\x17\n" +
	"\asrc_key\x18\x02 \x01(\tR\x06srcKey\x12\x1d\n" +
	"\n" +
	"dst_bucket\x18\x03 \x01(\tR\tdstBucket\x12\x17\n" +
	"\adst_key\x18\x04 \x01(\tR\x06dstKey\x12D\n" +
	"\aoptions\x18\x05 \x03(\v2*.storage.v1.CopyObjectRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x85\x02\n" +
	"\x11MoveObjectRequest\x12\x1d\n" +
	"\n" +
	"src_bucket\x18\x01 \x01(\tR\tsrcBucket\x12\x17\n" +
	"\asrc_key\x18\x02 \x01(\tR\x06srcKey\x12\x1d\n" +
	"\n" +
	"dst_bucket\x18\x03 \x01(\tR\tdstBucket\x12\x17\n" +
	"\adst_key\x18\x04 \x01(\tR\x06dstKey\x12D\n" +
	"\aoptions\x18\x05 \x03(\v2*.storage.v1.MoveObjectRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x12ListObjectsRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12E\n" +
	"\aoptions\x18\x05 \x03(\v2+.storage.v1.ListObjectsRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xef\x01\n" +
	"\x11ReadObjectRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\x12D\n" +
	"\aoptions\x18\x05 \x03(\v2*.storage.v1.ReadObjectRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"k\n" +
	"\x12ReadObjectResponse\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.storage.v1.ObjectInfoH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"t\n" +
	"\x12WriteObjectRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.storage.v1.WriteObjectMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\xfa\x01\n" +
	"\x13WriteObjectMetadata\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12F\n" +
	"\aoptions\x18\x05 \x03(\v2,.storage.v1.WriteObjectMetadata.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x14InitMultipartRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12G\n" +
	"\aoptions\x18\x04 \x03(\v2-.storage.v1.InitMultipartRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"r\n" +
	"\x11UploadPartRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.storage.v1.UploadPartMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x93\x02\n" +
	"\x12UploadPartMetadata\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12\x1f\n" +
	"\vpart_number\x18\x04 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12E\n" +
	"\aoptions\x18\x06 \x03(\v2+.storage.v1.UploadPartMetadata.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x88\x02\n" +
	"\x10ListPartsRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12C\n" +
	"\aoptions\x18\x06 \x03(\v2).storage.v1.ListPartsRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x96\x02\n" +
	"\x18CompleteMultipartRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12*\n" +
	"\x05parts\x18\x04 \x03(\v2\x14.storage.v1.PartInfoR\x05parts\x12K\n" +
	"\aoptions\x18\x05 \x03(\v21.storage.v1.CompleteMultipartRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x15AbortMultipartRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12H\n" +
	"\aoptions\x18\x04 \x03(\v2..storage.v1.AbortMultipartRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x8a\x02\n" +
	"\x10SignedURLRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x123\n" +
	"\aexpires\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\aexpires\x12C\n" +
	"\aoptions\x18\x05 \x03(\v2).storage.v1.SignedURLRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"%\n" +
	"\x11SignedURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12GetFeaturesRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket2\xae\n" +
	"\n" +
	"\x0eStorageService\x12G\n" +
	"\fCreateBucket\x12\x1f.storage.v1.CreateBucketRequest\x1a\x16.storage.v1.BucketInfo\x12G\n" +
	"\fDeleteBucket\x12\x1f.storage.v1.DeleteBucketRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\tGetBucket\x12\x1c.storage.v1.GetBucketRequest\x1a\x16.storage.v1.BucketInfo\x12G\n" +
	"\vListBuckets\x12\x1e.storage.v1.ListBucketsRequest\x1a\x16.storage.v1.BucketInfo0\x01\x12C\n" +
	"\n" +
	"StatObject\x12\x1d.storage.v1.StatObjectRequest\x1a\x16.storage.v1.ObjectInfo\x12G\n" +
	"\fDeleteObject\x12\x1f.storage.v1.DeleteObjectRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"CopyObject\x12\x1d.storage.v1.CopyObjectRequest\x1a\x16.storage.v1.ObjectInfo\x12C\n" +
	"\n" +
	"MoveObject\x12\x1d.storage.v1.MoveObjectRequest\x1a\x16.storage.v1.ObjectInfo\x12G\n" +
	"\vListObjects\x12\x1e.storage.v1.ListObjectsRequest\x1a\x16.storage.v1.ObjectInfo0\x01\x12M\n" +
	"\n" +
	"ReadObject\x12\x1d.storage.v1.ReadObjectRequest\x1a\x1e.storage.v1.ReadObjectResponse0\x01\x12G\n" +
	"\vWriteObject\x12\x1e.storage.v1.WriteObjectRequest\x1a\x16.storage.v1.ObjectInfo(\x01\x12N\n" +
	"\rInitMultipart\x12 .storage.v1.InitMultipartRequest\x1a\x1b.storage.v1.MultipartUpload\x12C\n" +
	"\n" +
	"UploadPart\x12\x1d.storage.v1.UploadPartRequest\x1a\x14.storage.v1.PartInfo(\x01\x12A\n" +
	"\tListParts\x12\x1c.storage.v1.ListPartsRequest\x1a\x14.storage.v1.PartInfo0\x01\x12Q\n" +
	"\x11CompleteMultipart\x12$.storage.v1.CompleteMultipartRequest\x1a\x16.storage.v1.ObjectInfo\x12K\n" +
	"\x0eAbortMultipart\x12!.storage.v1.AbortMultipartRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\tSignedURL\x12\x1c.storage.v1.SignedURLRequest\x1a\x1d.storage.v1.SignedURLResponse\x12C\n" +
	"\vGetFeatures\x12\x1e.storage.v1.GetFeaturesRequest\x1a\x14.storage.v1.FeaturesBJZHgithub.com/go-mizu/blueprints/localflare/pkg/storage/transport/grpc/storagepbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_storage_proto_goTypes = []any{
	(*BucketInfo)(nil),               // 0: storage.v1.BucketInfo
	(*ObjectInfo)(nil),               // 1: storage.v1.ObjectInfo
	(*MultipartUpload)(nil),          // 2: storage.v1.MultipartUpload
	(*PartInfo)(nil),                 // 3: storage.v1.PartInfo
	(*Features)(nil),                 // 4: storage.v1.Features
	(*CreateBucketRequest)(nil),      // 5: storage.v1.CreateBucketRequest
	(*DeleteBucketRequest)(nil),      // 6: storage.v1.DeleteBucketRequest
	(*GetBucketRequest)(nil),         // 7: storage.v1.GetBucketRequest
	(*ListBucketsRequest)(nil),       // 8: storage.v1.ListBucketsRequest
	(*StatObjectRequest)(nil),        // 9: storage.v1.StatObjectRequest
	(*DeleteObjectRequest)(nil),      // 10: storage.v1.DeleteObjectRequest
	(*CopyObjectRequest)(nil),        // 11: storage.v1.CopyObjectRequest
	(*MoveObjectRequest)(nil),        // 12: storage.v1.MoveObjectRequest
	(*ListObjectsRequest)(nil),       // 13: storage.v1.ListObjectsRequest
	(*ReadObjectRequest)(nil),        // 14: storage.v1.ReadObjectRequest
	(*ReadObjectResponse)(nil),       // 15: storage.v1.ReadObjectResponse
	(*WriteObjectRequest)(nil),       // 16: storage.v1.WriteObjectRequest
	(*WriteObjectMetadata)(nil),      // 17: storage.v1.WriteObjectMetadata
	(*InitMultipartRequest)(nil),     // 18: storage.v1.InitMultipartRequest
	(*UploadPartRequest)(nil),        // 19: storage.v1.UploadPartRequest
	(*UploadPartMetadata)(nil),       // 20: storage.v1.UploadPartMetadata
	(*ListPartsRequest)(nil),         // 21: storage.v1.ListPartsRequest
	(*CompleteMultipartRequest)(nil), // 22: storage.v1.CompleteMultipartRequest
	(*AbortMultipartRequest)(nil),    // 23: storage.v1.AbortMultipartRequest
	(*SignedURLRequest)(nil),         // 24: storage.v1.SignedURLRequest
	(*SignedURLResponse)(nil),        // 25: storage.v1.SignedURLResponse
	(*GetFeaturesRequest)(nil),       // 26: storage.v1.GetFeaturesRequest
	nil,                              // 27: storage.v1.BucketInfo.MetadataEntry
	nil,                              // 28: storage.v1.ObjectInfo.HashEntry
	nil,                              // 29: storage.v1.ObjectInfo.MetadataEntry
	nil,                              // 30: storage.v1.MultipartUpload.MetadataEntry
	nil,                              // 31: storage.v1.PartInfo.HashEntry
	nil,                              // 32: storage.v1.Features.FeaturesEntry
	nil,                              // 33: storage.v1.CreateBucketRequest.OptionsEntry
	nil,                              // 34: storage.v1.DeleteBucketRequest.OptionsEntry
	nil,                              // 35: storage.v1.ListBucketsRequest.OptionsEntry
	nil,                              // 36: storage.v1.StatObjectRequest.OptionsEntry
	nil,                              // 37: storage.v1.DeleteObjectRequest.OptionsEntry
	nil,                              // 38: storage.v1.CopyObjectRequest.OptionsEntry
	nil,                              // 39: storage.v1.MoveObjectRequest.OptionsEntry
	nil,                              // 40: storage.v1.ListObjectsRequest.OptionsEntry
	nil,                              // 41: storage.v1.ReadObjectRequest.OptionsEntry
	nil,                              // 42: storage.v1.WriteObjectMetadata.OptionsEntry
	nil,                              // 43: storage.v1.InitMultipartRequest.OptionsEntry
	nil,                              // 44: storage.v1.UploadPartMetadata.OptionsEntry
	nil,                              // 45: storage.v1.ListPartsRequest.OptionsEntry
	nil,                              // 46: storage.v1.CompleteMultipartRequest.OptionsEntry
	nil,                              // 47: storage.v1.AbortMultipartRequest.OptionsEntry
	nil,                              // 48: storage.v1.SignedURLRequest.OptionsEntry
	(*timestamppb.Timestamp)(nil),    // 49: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 50: google.protobuf.Duration
	(*emptypb.Empty)(nil),            // 51: google.protobuf.Empty
}
var file_storage_proto_depIdxs = []int32{
	49, // 0: storage.v1.BucketInfo.created_at:type_name -> google.protobuf.Timestamp
	27, // 1: storage.v1.BucketInfo.metadata:type_name -> storage.v1.BucketInfo.MetadataEntry
	49, // 2: storage.v1.ObjectInfo.created:type_name -> google.protobuf.Timestamp
	49, // 3: storage.v1.ObjectInfo.updated:type_name -> google.protobuf.Timestamp
	28, // 4: storage.v1.ObjectInfo.hash:type_name -> storage.v1.ObjectInfo.HashEntry
	29, // 5: storage.v1.ObjectInfo.metadata:type_name -> storage.v1.ObjectInfo.MetadataEntry
	30, // 6: storage.v1.MultipartUpload.metadata:type_name -> storage.v1.MultipartUpload.MetadataEntry
	31, // 7: storage.v1.PartInfo.hash:type_name -> storage.v1.PartInfo.HashEntry
	49, // 8: storage.v1.PartInfo.last_modified:type_name -> google.protobuf.Timestamp
	32, // 9: storage.v1.Features.features:type_name -> storage.v1.Features.FeaturesEntry
	33, // 10: storage.v1.CreateBucketRequest.options:type_name -> storage.v1.CreateBucketRequest.OptionsEntry
	34, // 11: storage.v1.DeleteBucketRequest.options:type_name -> storage.v1.DeleteBucketRequest.OptionsEntry
	35, // 12: storage.v1.ListBucketsRequest.options:type_name -> storage.v1.ListBucketsRequest.OptionsEntry
	36, // 13: storage.v1.StatObjectRequest.options:type_name -> storage.v1.StatObjectRequest.OptionsEntry
	37, // 14: storage.v1.DeleteObjectRequest.options:type_name -> storage.v1.DeleteObjectRequest.OptionsEntry
	38, // 15: storage.v1.CopyObjectRequest.options:type_name -> storage.v1.CopyObjectRequest.OptionsEntry
	39, // 16: storage.v1.MoveObjectRequest.options:type_name -> storage.v1.MoveObjectRequest.OptionsEntry
	40, // 17: storage.v1.ListObjectsRequest.options:type_name -> storage.v1.ListObjectsRequest.OptionsEntry
	41, // 18: storage.v1.ReadObjectRequest.options:type_name -> storage.v1.ReadObjectRequest.OptionsEntry
	1,  // 19: storage.v1.ReadObjectResponse.metadata:type_name -> storage.v1.ObjectInfo
	17, // 20: storage.v1.WriteObjectRequest.metadata:type_name -> storage.v1.WriteObjectMetadata
	42, // 21: storage.v1.WriteObjectMetadata.options:type_name -> storage.v1.WriteObjectMetadata.OptionsEntry
	43, // 22: storage.v1.InitMultipartRequest.options:type_name -> storage.v1.InitMultipartRequest.OptionsEntry
	20, // 23: storage.v1.UploadPartRequest.metadata:type_name -> storage.v1.UploadPartMetadata
	44, // 24: storage.v1.UploadPartMetadata.options:type_name -> storage.v1.UploadPartMetadata.OptionsEntry
	45, // 25: storage.v1.ListPartsRequest.options:type_name -> storage.v1.ListPartsRequest.OptionsEntry
	3,  // 26: storage.v1.CompleteMultipartRequest.parts:type_name -> storage.v1.PartInfo
	46, // 27: storage.v1.CompleteMultipartRequest.options:type_name -> storage.v1.CompleteMultipartRequest.OptionsEntry
	47, // 28: storage.v1.AbortMultipartRequest.options:type_name -> storage.v1.AbortMultipartRequest.OptionsEntry
	50, // 29: storage.v1.SignedURLRequest.expires:type_name -> google.protobuf.Duration
	48, // 30: storage.v1.SignedURLRequest.options:type_name -> storage.v1.SignedURLRequest.OptionsEntry
	5,  // 31: storage.v1.StorageService.CreateBucket:input_type -> storage.v1.CreateBucketRequest
	6,  // 32: storage.v1.StorageService.DeleteBucket:input_type -> storage.v1.DeleteBucketRequest
	7,  // 33: storage.v1.StorageService.GetBucket:input_type -> storage.v1.GetBucketRequest
	8,  // 34: storage.v1.StorageService.ListBuckets:input_type -> storage.v1.ListBucketsRequest
	9,  // 35: storage.v1.StorageService.StatObject:input_type -> storage.v1.StatObjectRequest
	10, // 36: storage.v1.StorageService.DeleteObject:input_type -> storage.v1.DeleteObjectRequest
	11, // 37: storage.v1.StorageService.CopyObject:input_type -> storage.v1.CopyObjectRequest
	12, // 38: storage.v1.StorageService.MoveObject:input_type -> storage.v1.MoveObjectRequest
	13, // 39: storage.v1.StorageService.ListObjects:input_type -> storage.v1.ListObjectsRequest
	14, // 40: storage.v1.StorageService.ReadObject:input_type -> storage.v1.ReadObjectRequest
	16, // 41: storage.v1.StorageService.WriteObject:input_type -> storage.v1.WriteObjectRequest
	18, // 42: storage.v1.StorageService.InitMultipart:input_type -> storage.v1.InitMultipartRequest
	19, // 43: storage.v1.StorageService.UploadPart:input_type -> storage.v1.UploadPartRequest
	21, // 44: storage.v1.StorageService.ListParts:input_type -> storage.v1.ListPartsRequest
	22, // 45: storage.v1.StorageService.CompleteMultipart:input_type -> storage.v1.CompleteMultipartRequest
	23, // 46: storage.v1.StorageService.AbortMultipart:input_type -> storage.v1.AbortMultipartRequest
	24, // 47: storage.v1.StorageService.SignedURL:input_type -> storage.v1.SignedURLRequest
	26, // 48: storage.v1.StorageService.GetFeatures:input_type -> storage.v1.GetFeaturesRequest
	0,  // 49: storage.v1.StorageService.CreateBucket:output_type -> storage.v1.BucketInfo
	51, // 50: storage.v1.StorageService.DeleteBucket:output_type -> google.protobuf.Empty
	0,  // 51: storage.v1.StorageService.GetBucket:output_type -> storage.v1.BucketInfo
	0,  // 52: storage.v1.StorageService.ListBuckets:output_type -> storage.v1.BucketInfo
	1,  // 53: storage.v1.StorageService.StatObject:output_type -> storage.v1.ObjectInfo
	51, // 54: storage.v1.StorageService.DeleteObject:output_type -> google.protobuf.Empty
	1,  // 55: storage.v1.StorageService.CopyObject:output_type -> storage.v1.ObjectInfo
	1,  // 56: storage.v1.StorageService.MoveObject:output_type -> storage.v1.ObjectInfo
	1,  // 57: storage.v1.StorageService.ListObjects:output_type -> storage.v1.ObjectInfo
	15, // 58: storage.v1.StorageService.ReadObject:output_type -> storage.v1.ReadObjectResponse
	1,  // 59: storage.v1.StorageService.WriteObject:output_type -> storage.v1.ObjectInfo
	2,  // 60: storage.v1.StorageService.InitMultipart:output_type -> storage.v1.MultipartUpload
	3,  // 61: storage.v1.StorageService.UploadPart:output_type -> storage.v1.PartInfo
	3,  // 62: storage.v1.StorageService.ListParts:output_type -> storage.v1.PartInfo
	1,  // 63: storage.v1.StorageService.CompleteMultipart:output_type -> storage.v1.ObjectInfo
	51, // 64: storage.v1.StorageService.AbortMultipart:output_type -> google.protobuf.Empty
	25, // 65: storage.v1.StorageService.SignedURL:output_type -> storage.v1.SignedURLResponse
	4,  // 66: storage.v1.StorageService.GetFeatures:output_type -> storage.v1.Features
	49, // [49:67] is the sub-list for method output_type
	31, // [31:49] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_storage_proto_msgTypes[15].OneofWrappers = []any{
		(*ReadObjectResponse_Metadata)(nil),
		(*ReadObjectResponse_Data)(nil),
	}
	file_storage_proto_msgTypes[16].OneofWrappers = []any{
		(*WriteObjectRequest_Metadata)(nil),
		(*WriteObjectRequest_Data)(nil),
	}
	file_storage_proto_msgTypes[19].OneofWrappers = []any{
		(*UploadPartRequest_Metadata)(nil),
		(*UploadPartRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
