package adapters

import (
	"github.com/go-mizu/mizu"
	"github.com/go-mizu/mizu/frontend"
)

// AngularOptions extends frontend.Options with Angular-specific settings.
type AngularOptions struct {
	frontend.Options

	// SSR indicates this is an Angular Universal SSR application.
	// Default: false
	SSR bool
}

// Angular creates a frontend middleware optimized for Angular applications.
//
// Angular-specific optimizations:
//   - Dev server: http://localhost:4200 (Angular CLI default)
//   - Build output: dist/<project-name>/browser
//   - Handles Angular's lazy loading patterns
//
// Example:
//
//	app.Use(adapters.Angular(frontend.Options{
//	    Root:      "./dist/my-app/browser",
//	    DevServer: "http://localhost:4200",
//	}))
func Angular(opts frontend.Options) mizu.Middleware {
	return AngularWithOptions(AngularOptions{Options: opts})
}

// AngularWithOptions creates an Angular middleware with extended options.
func AngularWithOptions(opts AngularOptions) mizu.Middleware {
	opts.Options = applyAngularDefaults(opts)

	return frontend.WithOptions(opts.Options)
}

func applyAngularDefaults(opts AngularOptions) frontend.Options {
	o := opts.Options

	// Angular CLI uses port 4200 by default
	if o.DevServer == "" {
		o.DevServer = "http://localhost:4200"
	}

	// Angular uses webpack, not Vite (by default)
	// Angular doesn't have a standard manifest path like Vite
	// Assets are directly in the output directory

	return o
}

// AngularUniversal creates a frontend middleware for Angular Universal SSR.
//
// Note: For full Angular Universal features, consider running the Express
// server generated by Angular Universal and proxying to Mizu for custom APIs.
func AngularUniversal(opts frontend.Options) mizu.Middleware {
	if opts.Root == "" {
		opts.Root = "dist/browser"
	}

	return AngularWithOptions(AngularOptions{
		Options: opts,
		SSR:     true,
	})
}
